const date_formats = [
    // date only
    "D-M",
    "D-Mo",
    "D-MM",
    "D-MMM",
    "D-MMMM",
    "Do-M",
    "Do-Mo",
    "Do-MM",
    "Do-MMM",
    "Do-MMMM",
    "DD-M",
    "DD-Mo",
    "DD-MM",
    "DD-MMM",
    "DD-MMMM",
    "M-YY",
    "M-YYYY",
    "Mo-YY",
    "Mo-YYYY",
    "MM-YY",
    "MM-YYYY",
    "MMM-YY",
    "MMM-YYYY",
    "MMMM-YY",
    "MMMM-YYYY",
    "D-M-YY",
    "D-M-YYYY",
    "D-Mo-YY",
    "D-Mo-YYYY",
    "D-MM-YY",
    "D-MM-YYYY",
    "D-MMM-YY",
    "D-MMM-YYYY",
    "D-MMMM-YY",
    "D-MMMM-YYYY",
    "Do-M-YY",
    "Do-M-YYYY",
    "Do-Mo-YY",
    "Do-Mo-YYYY",
    "Do-MM-YY",
    "Do-MM-YYYY",
    "Do-MMM-YY",
    "Do-MMM-YYYY",
    "Do-MMMM-YY",
    "Do-MMMM-YYYY",
    "DD-M-YY",
    "DD-M-YYYY",
    "DD-Mo-YY",
    "DD-Mo-YYYY",
    "DD-MM-YY",
    "DD-MM-YYYY",
    "DD-MMM-YY",
    "DD-MMM-YYYY",
    "DD-MMMM-YY",
    "DD-MMMM-YYYY",
    "M-D-YY",
    "M-D-YYYY",
    "M-Do-YY",
    "M-Do-YYYY",
    "M-DD-YY",
    "M-DD-YYYY",
    "Mo-D-YY",
    "Mo-D-YYYY",
    "Mo-Do-YY",
    "Mo-Do-YYYY",
    "Mo-DD-YY",
    "Mo-DD-YYYY",
    "MM-D-YY",
    "MM-D-YYYY",
    "MM-Do-YY",
    "MM-Do-YYYY",
    "MM-DD-YY",
    "MM-DD-YYYY",
    "MMM-D-YY",
    "MMM-D-YYYY",
    "MMM-Do-YY",
    "MMM-Do-YYYY",
    "MMM-DD-YY",
    "MMM-DD-YYYY",
    "MMMM-D-YY",
    "MMMM-D-YYYY",
    "MMMM-Do-YY",
    "MMMM-Do-YYYY",
    "MMMM-DD-YY",
    "MMMM-DD-YYYY",
    "M-D",
    "M-Do",
    "M-DD",
    "Mo-D",
    "Mo-Do",
    "Mo-DD",
    "MM-D",
    "MM-Do",
    "MM-DD",
    "MMM-D",
    "MMM-Do",
    "MMM-DD",
    "MMMM-D",
    "MMMM-Do",
    "MMMM-DD",
    "YY-M",
    "YY-Mo",
    "YY-MM",
    "YY-MMM",
    "YY-MMMM",
    "YYYY-M",
    "YYYY-Mo",
    "YYYY-MM",
    "YYYY-MMM",
    "YYYY-MMMM",
    "YY-M-D",
    "YY-M-Do",
    "YY-M-DD",
    "YY-Mo-D",
    "YY-Mo-Do",
    "YY-Mo-DD",
    "YY-MM-D",
    "YY-MM-Do",
    "YY-MM-DD",
    "YY-MMM-D",
    "YY-MMM-Do",
    "YY-MMM-DD",
    "YY-MMMM-D",
    "YY-MMMM-Do",
    "YY-MMMM-DD",
    "YYYY-M-D",
    "YYYY-M-Do",
    "YYYY-M-DD",
    "YYYY-Mo-D",
    "YYYY-Mo-Do",
    "YYYY-Mo-DD",
    "YYYY-MM-D",
    "YYYY-MM-Do",
    "YYYY-MM-DD",
    "YYYY-MMM-D",
    "YYYY-MMM-Do",
    "YYYY-MMM-DD",
    "YYYY-MMMM-D",
    "YYYY-MMMM-Do",
    "YYYY-MMMM-DD",
    "YY-D-M",
    "YY-D-Mo",
    "YY-D-MM",
    "YY-D-MMM",
    "YY-D-MMMM",
    "YY-Do-M",
    "YY-Do-Mo",
    "YY-Do-MM",
    "YY-Do-MMM",
    "YY-Do-MMMM",
    "YY-DD-M",
    "YY-DD-Mo",
    "YY-DD-MM",
    "YY-DD-MMM",
    "YY-DD-MMMM",
    "YYYY-D-M",
    "YYYY-D-Mo",
    "YYYY-D-MM",
    "YYYY-D-MMM",
    "YYYY-D-MMMM",
    "YYYY-Do-M",
    "YYYY-Do-Mo",
    "YYYY-Do-MM",
    "YYYY-Do-MMM",
    "YYYY-Do-MMMM",
    "YYYY-DD-M",
    "YYYY-DD-Mo",
    "YYYY-DD-MM",
    "YYYY-DD-MMM",
    "YYYY-DD-MMMM",
    "D/M",
    "D/Mo",
    "D/MM",
    "D/MMM",
    "D/MMMM",
    "Do/M",
    "Do/Mo",
    "Do/MM",
    "Do/MMM",
    "Do/MMMM",
    "DD/M",
    "DD/Mo",
    "DD/MM",
    "DD/MMM",
    "DD/MMMM",
    "M/YY",
    "M/YYYY",
    "Mo/YY",
    "Mo/YYYY",
    "MM/YY",
    "MM/YYYY",
    "MMM/YY",
    "MMM/YYYY",
    "MMMM/YY",
    "MMMM/YYYY",
    "D/M/YY",
    "D/M/YYYY",
    "D/Mo/YY",
    "D/Mo/YYYY",
    "D/MM/YY",
    "D/MM/YYYY",
    "D/MMM/YY",
    "D/MMM/YYYY",
    "D/MMMM/YY",
    "D/MMMM/YYYY",
    "Do/M/YY",
    "Do/M/YYYY",
    "Do/Mo/YY",
    "Do/Mo/YYYY",
    "Do/MM/YY",
    "Do/MM/YYYY",
    "Do/MMM/YY",
    "Do/MMM/YYYY",
    "Do/MMMM/YY",
    "Do/MMMM/YYYY",
    "DD/M/YY",
    "DD/M/YYYY",
    "DD/Mo/YY",
    "DD/Mo/YYYY",
    "DD/MM/YY",
    "DD/MM/YYYY",
    "DD/MMM/YY",
    "DD/MMM/YYYY",
    "DD/MMMM/YY",
    "DD/MMMM/YYYY",
    "M/D/YY",
    "M/D/YYYY",
    "M/Do/YY",
    "M/Do/YYYY",
    "M/DD/YY",
    "M/DD/YYYY",
    "Mo/D/YY",
    "Mo/D/YYYY",
    "Mo/Do/YY",
    "Mo/Do/YYYY",
    "Mo/DD/YY",
    "Mo/DD/YYYY",
    "MM/D/YY",
    "MM/D/YYYY",
    "MM/Do/YY",
    "MM/Do/YYYY",
    "MM/DD/YY",
    "MM/DD/YYYY",
    "MMM/D/YY",
    "MMM/D/YYYY",
    "MMM/Do/YY",
    "MMM/Do/YYYY",
    "MMM/DD/YY",
    "MMM/DD/YYYY",
    "MMMM/D/YY",
    "MMMM/D/YYYY",
    "MMMM/Do/YY",
    "MMMM/Do/YYYY",
    "MMMM/DD/YY",
    "MMMM/DD/YYYY",
    "M/D",
    "M/Do",
    "M/DD",
    "Mo/D",
    "Mo/Do",
    "Mo/DD",
    "MM/D",
    "MM/Do",
    "MM/DD",
    "MMM/D",
    "MMM/Do",
    "MMM/DD",
    "MMMM/D",
    "MMMM/Do",
    "MMMM/DD",
    "YY/M",
    "YY/Mo",
    "YY/MM",
    "YY/MMM",
    "YY/MMMM",
    "YYYY/M",
    "YYYY/Mo",
    "YYYY/MM",
    "YYYY/MMM",
    "YYYY/MMMM",
    "YY/M/D",
    "YY/M/Do",
    "YY/M/DD",
    "YY/Mo/D",
    "YY/Mo/Do",
    "YY/Mo/DD",
    "YY/MM/D",
    "YY/MM/Do",
    "YY/MM/DD",
    "YY/MMM/D",
    "YY/MMM/Do",
    "YY/MMM/DD",
    "YY/MMMM/D",
    "YY/MMMM/Do",
    "YY/MMMM/DD",
    "YYYY/M/D",
    "YYYY/M/Do",
    "YYYY/M/DD",
    "YYYY/Mo/D",
    "YYYY/Mo/Do",
    "YYYY/Mo/DD",
    "YYYY/MM/D",
    "YYYY/MM/Do",
    "YYYY/MM/DD",
    "YYYY/MMM/D",
    "YYYY/MMM/Do",
    "YYYY/MMM/DD",
    "YYYY/MMMM/D",
    "YYYY/MMMM/Do",
    "YYYY/MMMM/DD",
    "YY/D/M",
    "YY/D/Mo",
    "YY/D/MM",
    "YY/D/MMM",
    "YY/D/MMMM",
    "YY/Do/M",
    "YY/Do/Mo",
    "YY/Do/MM",
    "YY/Do/MMM",
    "YY/Do/MMMM",
    "YY/DD/M",
    "YY/DD/Mo",
    "YY/DD/MM",
    "YY/DD/MMM",
    "YY/DD/MMMM",
    "YYYY/D/M",
    "YYYY/D/Mo",
    "YYYY/D/MM",
    "YYYY/D/MMM",
    "YYYY/D/MMMM",
    "YYYY/Do/M",
    "YYYY/Do/Mo",
    "YYYY/Do/MM",
    "YYYY/Do/MMM",
    "YYYY/Do/MMMM",
    "YYYY/DD/M",
    "YYYY/DD/Mo",
    "YYYY/DD/MM",
    "YYYY/DD/MMM",
    "YYYY/DD/MMMM",
    "D.M",
    "D.Mo",
    "D.MM",
    "D.MMM",
    "D.MMMM",
    "Do.M",
    "Do.Mo",
    "Do.MM",
    "Do.MMM",
    "Do.MMMM",
    "DD.M",
    "DD.Mo",
    "DD.MM",
    "DD.MMM",
    "DD.MMMM",
    "M.YY",
    "M.YYYY",
    "Mo.YY",
    "Mo.YYYY",
    "MM.YY",
    "MM.YYYY",
    "MMM.YY",
    "MMM.YYYY",
    "MMMM.YY",
    "MMMM.YYYY",
    "D.M.YY",
    "D.M.YYYY",
    "D.Mo.YY",
    "D.Mo.YYYY",
    "D.MM.YY",
    "D.MM.YYYY",
    "D.MMM.YY",
    "D.MMM.YYYY",
    "D.MMMM.YY",
    "D.MMMM.YYYY",
    "Do.M.YY",
    "Do.M.YYYY",
    "Do.Mo.YY",
    "Do.Mo.YYYY",
    "Do.MM.YY",
    "Do.MM.YYYY",
    "Do.MMM.YY",
    "Do.MMM.YYYY",
    "Do.MMMM.YY",
    "Do.MMMM.YYYY",
    "DD.M.YY",
    "DD.M.YYYY",
    "DD.Mo.YY",
    "DD.Mo.YYYY",
    "DD.MM.YY",
    "DD.MM.YYYY",
    "DD.MMM.YY",
    "DD.MMM.YYYY",
    "DD.MMMM.YY",
    "DD.MMMM.YYYY",
    "M.D.YY",
    "M.D.YYYY",
    "M.Do.YY",
    "M.Do.YYYY",
    "M.DD.YY",
    "M.DD.YYYY",
    "Mo.D.YY",
    "Mo.D.YYYY",
    "Mo.Do.YY",
    "Mo.Do.YYYY",
    "Mo.DD.YY",
    "Mo.DD.YYYY",
    "MM.D.YY",
    "MM.D.YYYY",
    "MM.Do.YY",
    "MM.Do.YYYY",
    "MM.DD.YY",
    "MM.DD.YYYY",
    "MMM.D.YY",
    "MMM.D.YYYY",
    "MMM.Do.YY",
    "MMM.Do.YYYY",
    "MMM.DD.YY",
    "MMM.DD.YYYY",
    "MMMM.D.YY",
    "MMMM.D.YYYY",
    "MMMM.Do.YY",
    "MMMM.Do.YYYY",
    "MMMM.DD.YY",
    "MMMM.DD.YYYY",
    "M.D",
    "M.Do",
    "M.DD",
    "Mo.D",
    "Mo.Do",
    "Mo.DD",
    "MM.D",
    "MM.Do",
    "MM.DD",
    "MMM.D",
    "MMM.Do",
    "MMM.DD",
    "MMMM.D",
    "MMMM.Do",
    "MMMM.DD",
    "YY.M",
    "YY.Mo",
    "YY.MM",
    "YY.MMM",
    "YY.MMMM",
    "YYYY.M",
    "YYYY.Mo",
    "YYYY.MM",
    "YYYY.MMM",
    "YYYY.MMMM",
    "YY.M.D",
    "YY.M.Do",
    "YY.M.DD",
    "YY.Mo.D",
    "YY.Mo.Do",
    "YY.Mo.DD",
    "YY.MM.D",
    "YY.MM.Do",
    "YY.MM.DD",
    "YY.MMM.D",
    "YY.MMM.Do",
    "YY.MMM.DD",
    "YY.MMMM.D",
    "YY.MMMM.Do",
    "YY.MMMM.DD",
    "YYYY.M.D",
    "YYYY.M.Do",
    "YYYY.M.DD",
    "YYYY.Mo.D",
    "YYYY.Mo.Do",
    "YYYY.Mo.DD",
    "YYYY.MM.D",
    "YYYY.MM.Do",
    "YYYY.MM.DD",
    "YYYY.MMM.D",
    "YYYY.MMM.Do",
    "YYYY.MMM.DD",
    "YYYY.MMMM.D",
    "YYYY.MMMM.Do",
    "YYYY.MMMM.DD",
    "YY.D.M",
    "YY.D.Mo",
    "YY.D.MM",
    "YY.D.MMM",
    "YY.D.MMMM",
    "YY.Do.M",
    "YY.Do.Mo",
    "YY.Do.MM",
    "YY.Do.MMM",
    "YY.Do.MMMM",
    "YY.DD.M",
    "YY.DD.Mo",
    "YY.DD.MM",
    "YY.DD.MMM",
    "YY.DD.MMMM",
    "YYYY.D.M",
    "YYYY.D.Mo",
    "YYYY.D.MM",
    "YYYY.D.MMM",
    "YYYY.D.MMMM",
    "YYYY.Do.M",
    "YYYY.Do.Mo",
    "YYYY.Do.MM",
    "YYYY.Do.MMM",
    "YYYY.Do.MMMM",
    "YYYY.DD.M",
    "YYYY.DD.Mo",
    "YYYY.DD.MM",
    "YYYY.DD.MMM",
    "YYYY.DD.MMMM",
    "D M",
    "D Mo",
    "D MM",
    "D MMM",
    "D MMMM",
    "Do M",
    "Do Mo",
    "Do MM",
    "Do MMM",
    "Do MMMM",
    "DD M",
    "DD Mo",
    "DD MM",
    "DD MMM",
    "DD MMMM",
    "M YY",
    "M YYYY",
    "Mo YY",
    "Mo YYYY",
    "MM YY",
    "MM YYYY",
    "MMM YY",
    "MMM YYYY",
    "MMMM YY",
    "MMMM YYYY",
    "D M YY",
    "D M YYYY",
    "D Mo YY",
    "D Mo YYYY",
    "D MM YY",
    "D MM YYYY",
    "D MMM YY",
    "D MMM YYYY",
    "D MMMM YY",
    "D MMMM YYYY",
    "Do M YY",
    "Do M YYYY",
    "Do Mo YY",
    "Do Mo YYYY",
    "Do MM YY",
    "Do MM YYYY",
    "Do MMM YY",
    "Do MMM YYYY",
    "Do MMMM YY",
    "Do MMMM YYYY",
    "DD M YY",
    "DD M YYYY",
    "DD Mo YY",
    "DD Mo YYYY",
    "DD MM YY",
    "DD MM YYYY",
    "DD MMM YY",
    "DD MMM YYYY",
    "DD MMMM YY",
    "DD MMMM YYYY",
    "M D YY",
    "M D YYYY",
    "M Do YY",
    "M Do YYYY",
    "M DD YY",
    "M DD YYYY",
    "Mo D YY",
    "Mo D YYYY",
    "Mo Do YY",
    "Mo Do YYYY",
    "Mo DD YY",
    "Mo DD YYYY",
    "MM D YY",
    "MM D YYYY",
    "MM Do YY",
    "MM Do YYYY",
    "MM DD YY",
    "MM DD YYYY",
    "MMM D YY",
    "MMM D YYYY",
    "MMM Do YY",
    "MMM Do YYYY",
    "MMM DD YY",
    "MMM DD YYYY",
    "MMMM D YY",
    "MMMM D YYYY",
    "MMMM Do YY",
    "MMMM Do YYYY",
    "MMMM DD YY",
    "MMMM DD YYYY",
    "M D",
    "M Do",
    "M DD",
    "Mo D",
    "Mo Do",
    "Mo DD",
    "MM D",
    "MM Do",
    "MM DD",
    "MMM D",
    "MMM Do",
    "MMM DD",
    "MMMM D",
    "MMMM Do",
    "MMMM DD",
    "YY M",
    "YY Mo",
    "YY MM",
    "YY MMM",
    "YY MMMM",
    "YYYY M",
    "YYYY Mo",
    "YYYY MM",
    "YYYY MMM",
    "YYYY MMMM",
    "YY M D",
    "YY M Do",
    "YY M DD",
    "YY Mo D",
    "YY Mo Do",
    "YY Mo DD",
    "YY MM D",
    "YY MM Do",
    "YY MM DD",
    "YY MMM D",
    "YY MMM Do",
    "YY MMM DD",
    "YY MMMM D",
    "YY MMMM Do",
    "YY MMMM DD",
    "YYYY M D",
    "YYYY M Do",
    "YYYY M DD",
    "YYYY Mo D",
    "YYYY Mo Do",
    "YYYY Mo DD",
    "YYYY MM D",
    "YYYY MM Do",
    "YYYY MM DD",
    "YYYY MMM D",
    "YYYY MMM Do",
    "YYYY MMM DD",
    "YYYY MMMM D",
    "YYYY MMMM Do",
    "YYYY MMMM DD",
    "YY D M",
    "YY D Mo",
    "YY D MM",
    "YY D MMM",
    "YY D MMMM",
    "YY Do M",
    "YY Do Mo",
    "YY Do MM",
    "YY Do MMM",
    "YY Do MMMM",
    "YY DD M",
    "YY DD Mo",
    "YY DD MM",
    "YY DD MMM",
    "YY DD MMMM",
    "YYYY D M",
    "YYYY D Mo",
    "YYYY D MM",
    "YYYY D MMM",
    "YYYY D MMMM",
    "YYYY Do M",
    "YYYY Do Mo",
    "YYYY Do MM",
    "YYYY Do MMM",
    "YYYY Do MMMM",
    "YYYY DD M",
    "YYYY DD Mo",
    "YYYY DD MM",
    "YYYY DD MMM",
    "YYYY DD MMMM",
    "DM",
    "DMo",
    "DMM",
    "DMMM",
    "DMMMM",
    "DoM",
    "DoMo",
    "DoMM",
    "DoMMM",
    "DoMMMM",
    "DDM",
    "DDMo",
    "DDMM",
    "DDMMM",
    "DDMMMM",
    "MYY",
    "MYYYY",
    "MoYY",
    "MoYYYY",
    "MMYY",
    "MMYYYY",
    "MMMYY",
    "MMMYYYY",
    "MMMMYY",
    "MMMMYYYY",
    "DMYY",
    "DMYYYY",
    "DMoYY",
    "DMoYYYY",
    "DMMYY",
    "DMMYYYY",
    "DMMMYY",
    "DMMMYYYY",
    "DMMMMYY",
    "DMMMMYYYY",
    "DoMYY",
    "DoMYYYY",
    "DoMoYY",
    "DoMoYYYY",
    "DoMMYY",
    "DoMMYYYY",
    "DoMMMYY",
    "DoMMMYYYY",
    "DoMMMMYY",
    "DoMMMMYYYY",
    "DDMYY",
    "DDMYYYY",
    "DDMoYY",
    "DDMoYYYY",
    "DDMMYY",
    "DDMMYYYY",
    "DDMMMYY",
    "DDMMMYYYY",
    "DDMMMMYY",
    "DDMMMMYYYY",
    "MDYY",
    "MDYYYY",
    "MDoYY",
    "MDoYYYY",
    "MDDYY",
    "MDDYYYY",
    "MoDYY",
    "MoDYYYY",
    "MoDoYY",
    "MoDoYYYY",
    "MoDDYY",
    "MoDDYYYY",
    "MMDYY",
    "MMDYYYY",
    "MMDoYY",
    "MMDoYYYY",
    "MMDDYY",
    "MMDDYYYY",
    "MMMDYY",
    "MMMDYYYY",
    "MMMDoYY",
    "MMMDoYYYY",
    "MMMDDYY",
    "MMMDDYYYY",
    "MMMMDYY",
    "MMMMDYYYY",
    "MMMMDoYY",
    "MMMMDoYYYY",
    "MMMMDDYY",
    "MMMMDDYYYY",
    "MD",
    "MDo",
    "MDD",
    "MoD",
    "MoDo",
    "MoDD",
    "MMD",
    "MMDo",
    "MMDD",
    "MMMD",
    "MMMDo",
    "MMMDD",
    "MMMMD",
    "MMMMDo",
    "MMMMDD",
    "YYM",
    "YYMo",
    "YYMM",
    "YYMMM",
    "YYMMMM",
    "YYYYM",
    "YYYYMo",
    "YYYYMM",
    "YYYYMMM",
    "YYYYMMMM",
    "YYMD",
    "YYMDo",
    "YYMDD",
    "YYMoD",
    "YYMoDo",
    "YYMoDD",
    "YYMMD",
    "YYMMDo",
    "YYMMDD",
    "YYMMMD",
    "YYMMMDo",
    "YYMMMDD",
    "YYMMMMD",
    "YYMMMMDo",
    "YYMMMMDD",
    "YYYYMD",
    "YYYYMDo",
    "YYYYMDD",
    "YYYYMoD",
    "YYYYMoDo",
    "YYYYMoDD",
    "YYYYMMD",
    "YYYYMMDo",
    "YYYYMMDD",
    "YYYYMMMD",
    "YYYYMMMDo",
    "YYYYMMMDD",
    "YYYYMMMMD",
    "YYYYMMMMDo",
    "YYYYMMMMDD",
    "YYDM",
    "YYDMo",
    "YYDMM",
    "YYDMMM",
    "YYDMMMM",
    "YYDoM",
    "YYDoMo",
    "YYDoMM",
    "YYDoMMM",
    "YYDoMMMM",
    "YYDDM",
    "YYDDMo",
    "YYDDMM",
    "YYDDMMM",
    "YYDDMMMM",
    "YYYYDM",
    "YYYYDMo",
    "YYYYDMM",
    "YYYYDMMM",
    "YYYYDMMMM",
    "YYYYDoM",
    "YYYYDoMo",
    "YYYYDoMM",
    "YYYYDoMMM",
    "YYYYDoMMMM",
    "YYYYDDM",
    "YYYYDDMo",
    "YYYYDDMM",
    "YYYYDDMMM",
    "YYYYDDMMMM",
    "M Do, YY",
    "M Do, YYYY",
    "Mo Do, YY",
    "Mo Do, YYYY",
    "MM Do, YY",
    "MM Do, YYYY",
    "MMM Do, YY",
    "MMM Do, YYYY",
    "MMMM Do, YY",
    "MMMM Do, YYYY",
    "M D, YY",
    "M D, YYYY",
    "Mo D, YY",
    "Mo D, YYYY",
    "MM D, YY",
    "MM D, YYYY",
    "MMM D, YY",
    "MMM D, YYYY",
    "MMMM D, YY",
    "MMMM D, YYYY",
    "M DD, YY",
    "M DD, YYYY",
    "Mo DD, YY",
    "Mo DD, YYYY",
    "MM DD, YY",
    "MM DD, YYYY",
    "MMM DD, YY",
    "MMM DD, YYYY",
    "MMMM DD, YY",
    "MMMM DD, YYYY",
    "ddd D-M",
    "ddd D-Mo",
    "ddd D-MM",
    "ddd D-MMM",
    "ddd D-MMMM",
    "ddd Do-M",
    "ddd Do-Mo",
    "ddd Do-MM",
    "ddd Do-MMM",
    "ddd Do-MMMM",
    "ddd DD-M",
    "ddd DD-Mo",
    "ddd DD-MM",
    "ddd DD-MMM",
    "ddd DD-MMMM",
    "ddd M-YY",
    "ddd M-YYYY",
    "ddd Mo-YY",
    "ddd Mo-YYYY",
    "ddd MM-YY",
    "ddd MM-YYYY",
    "ddd MMM-YY",
    "ddd MMM-YYYY",
    "ddd MMMM-YY",
    "ddd MMMM-YYYY",
    "ddd D-M-YY",
    "ddd D-M-YYYY",
    "ddd D-Mo-YY",
    "ddd D-Mo-YYYY",
    "ddd D-MM-YY",
    "ddd D-MM-YYYY",
    "ddd D-MMM-YY",
    "ddd D-MMM-YYYY",
    "ddd D-MMMM-YY",
    "ddd D-MMMM-YYYY",
    "ddd Do-M-YY",
    "ddd Do-M-YYYY",
    "ddd Do-Mo-YY",
    "ddd Do-Mo-YYYY",
    "ddd Do-MM-YY",
    "ddd Do-MM-YYYY",
    "ddd Do-MMM-YY",
    "ddd Do-MMM-YYYY",
    "ddd Do-MMMM-YY",
    "ddd Do-MMMM-YYYY",
    "ddd DD-M-YY",
    "ddd DD-M-YYYY",
    "ddd DD-Mo-YY",
    "ddd DD-Mo-YYYY",
    "ddd DD-MM-YY",
    "ddd DD-MM-YYYY",
    "ddd DD-MMM-YY",
    "ddd DD-MMM-YYYY",
    "ddd DD-MMMM-YY",
    "ddd DD-MMMM-YYYY",
    "ddd M-D-YY",
    "ddd M-D-YYYY",
    "ddd M-Do-YY",
    "ddd M-Do-YYYY",
    "ddd M-DD-YY",
    "ddd M-DD-YYYY",
    "ddd Mo-D-YY",
    "ddd Mo-D-YYYY",
    "ddd Mo-Do-YY",
    "ddd Mo-Do-YYYY",
    "ddd Mo-DD-YY",
    "ddd Mo-DD-YYYY",
    "ddd MM-D-YY",
    "ddd MM-D-YYYY",
    "ddd MM-Do-YY",
    "ddd MM-Do-YYYY",
    "ddd MM-DD-YY",
    "ddd MM-DD-YYYY",
    "ddd MMM-D-YY",
    "ddd MMM-D-YYYY",
    "ddd MMM-Do-YY",
    "ddd MMM-Do-YYYY",
    "ddd MMM-DD-YY",
    "ddd MMM-DD-YYYY",
    "ddd MMMM-D-YY",
    "ddd MMMM-D-YYYY",
    "ddd MMMM-Do-YY",
    "ddd MMMM-Do-YYYY",
    "ddd MMMM-DD-YY",
    "ddd MMMM-DD-YYYY",
    "ddd M-D",
    "ddd M-Do",
    "ddd M-DD",
    "ddd Mo-D",
    "ddd Mo-Do",
    "ddd Mo-DD",
    "ddd MM-D",
    "ddd MM-Do",
    "ddd MM-DD",
    "ddd MMM-D",
    "ddd MMM-Do",
    "ddd MMM-DD",
    "ddd MMMM-D",
    "ddd MMMM-Do",
    "ddd MMMM-DD",
    "ddd YY-M",
    "ddd YY-Mo",
    "ddd YY-MM",
    "ddd YY-MMM",
    "ddd YY-MMMM",
    "ddd YYYY-M",
    "ddd YYYY-Mo",
    "ddd YYYY-MM",
    "ddd YYYY-MMM",
    "ddd YYYY-MMMM",
    "ddd YY-M-D",
    "ddd YY-M-Do",
    "ddd YY-M-DD",
    "ddd YY-Mo-D",
    "ddd YY-Mo-Do",
    "ddd YY-Mo-DD",
    "ddd YY-MM-D",
    "ddd YY-MM-Do",
    "ddd YY-MM-DD",
    "ddd YY-MMM-D",
    "ddd YY-MMM-Do",
    "ddd YY-MMM-DD",
    "ddd YY-MMMM-D",
    "ddd YY-MMMM-Do",
    "ddd YY-MMMM-DD",
    "ddd YYYY-M-D",
    "ddd YYYY-M-Do",
    "ddd YYYY-M-DD",
    "ddd YYYY-Mo-D",
    "ddd YYYY-Mo-Do",
    "ddd YYYY-Mo-DD",
    "ddd YYYY-MM-D",
    "ddd YYYY-MM-Do",
    "ddd YYYY-MM-DD",
    "ddd YYYY-MMM-D",
    "ddd YYYY-MMM-Do",
    "ddd YYYY-MMM-DD",
    "ddd YYYY-MMMM-D",
    "ddd YYYY-MMMM-Do",
    "ddd YYYY-MMMM-DD",
    "ddd YY-D-M",
    "ddd YY-D-Mo",
    "ddd YY-D-MM",
    "ddd YY-D-MMM",
    "ddd YY-D-MMMM",
    "ddd YY-Do-M",
    "ddd YY-Do-Mo",
    "ddd YY-Do-MM",
    "ddd YY-Do-MMM",
    "ddd YY-Do-MMMM",
    "ddd YY-DD-M",
    "ddd YY-DD-Mo",
    "ddd YY-DD-MM",
    "ddd YY-DD-MMM",
    "ddd YY-DD-MMMM",
    "ddd YYYY-D-M",
    "ddd YYYY-D-Mo",
    "ddd YYYY-D-MM",
    "ddd YYYY-D-MMM",
    "ddd YYYY-D-MMMM",
    "ddd YYYY-Do-M",
    "ddd YYYY-Do-Mo",
    "ddd YYYY-Do-MM",
    "ddd YYYY-Do-MMM",
    "ddd YYYY-Do-MMMM",
    "ddd YYYY-DD-M",
    "ddd YYYY-DD-Mo",
    "ddd YYYY-DD-MM",
    "ddd YYYY-DD-MMM",
    "ddd YYYY-DD-MMMM",
    "ddd D/M",
    "ddd D/Mo",
    "ddd D/MM",
    "ddd D/MMM",
    "ddd D/MMMM",
    "ddd Do/M",
    "ddd Do/Mo",
    "ddd Do/MM",
    "ddd Do/MMM",
    "ddd Do/MMMM",
    "ddd DD/M",
    "ddd DD/Mo",
    "ddd DD/MM",
    "ddd DD/MMM",
    "ddd DD/MMMM",
    "ddd M/YY",
    "ddd M/YYYY",
    "ddd Mo/YY",
    "ddd Mo/YYYY",
    "ddd MM/YY",
    "ddd MM/YYYY",
    "ddd MMM/YY",
    "ddd MMM/YYYY",
    "ddd MMMM/YY",
    "ddd MMMM/YYYY",
    "ddd D/M/YY",
    "ddd D/M/YYYY",
    "ddd D/Mo/YY",
    "ddd D/Mo/YYYY",
    "ddd D/MM/YY",
    "ddd D/MM/YYYY",
    "ddd D/MMM/YY",
    "ddd D/MMM/YYYY",
    "ddd D/MMMM/YY",
    "ddd D/MMMM/YYYY",
    "ddd Do/M/YY",
    "ddd Do/M/YYYY",
    "ddd Do/Mo/YY",
    "ddd Do/Mo/YYYY",
    "ddd Do/MM/YY",
    "ddd Do/MM/YYYY",
    "ddd Do/MMM/YY",
    "ddd Do/MMM/YYYY",
    "ddd Do/MMMM/YY",
    "ddd Do/MMMM/YYYY",
    "ddd DD/M/YY",
    "ddd DD/M/YYYY",
    "ddd DD/Mo/YY",
    "ddd DD/Mo/YYYY",
    "ddd DD/MM/YY",
    "ddd DD/MM/YYYY",
    "ddd DD/MMM/YY",
    "ddd DD/MMM/YYYY",
    "ddd DD/MMMM/YY",
    "ddd DD/MMMM/YYYY",
    "ddd M/D/YY",
    "ddd M/D/YYYY",
    "ddd M/Do/YY",
    "ddd M/Do/YYYY",
    "ddd M/DD/YY",
    "ddd M/DD/YYYY",
    "ddd Mo/D/YY",
    "ddd Mo/D/YYYY",
    "ddd Mo/Do/YY",
    "ddd Mo/Do/YYYY",
    "ddd Mo/DD/YY",
    "ddd Mo/DD/YYYY",
    "ddd MM/D/YY",
    "ddd MM/D/YYYY",
    "ddd MM/Do/YY",
    "ddd MM/Do/YYYY",
    "ddd MM/DD/YY",
    "ddd MM/DD/YYYY",
    "ddd MMM/D/YY",
    "ddd MMM/D/YYYY",
    "ddd MMM/Do/YY",
    "ddd MMM/Do/YYYY",
    "ddd MMM/DD/YY",
    "ddd MMM/DD/YYYY",
    "ddd MMMM/D/YY",
    "ddd MMMM/D/YYYY",
    "ddd MMMM/Do/YY",
    "ddd MMMM/Do/YYYY",
    "ddd MMMM/DD/YY",
    "ddd MMMM/DD/YYYY",
    "ddd M/D",
    "ddd M/Do",
    "ddd M/DD",
    "ddd Mo/D",
    "ddd Mo/Do",
    "ddd Mo/DD",
    "ddd MM/D",
    "ddd MM/Do",
    "ddd MM/DD",
    "ddd MMM/D",
    "ddd MMM/Do",
    "ddd MMM/DD",
    "ddd MMMM/D",
    "ddd MMMM/Do",
    "ddd MMMM/DD",
    "ddd YY/M",
    "ddd YY/Mo",
    "ddd YY/MM",
    "ddd YY/MMM",
    "ddd YY/MMMM",
    "ddd YYYY/M",
    "ddd YYYY/Mo",
    "ddd YYYY/MM",
    "ddd YYYY/MMM",
    "ddd YYYY/MMMM",
    "ddd YY/M/D",
    "ddd YY/M/Do",
    "ddd YY/M/DD",
    "ddd YY/Mo/D",
    "ddd YY/Mo/Do",
    "ddd YY/Mo/DD",
    "ddd YY/MM/D",
    "ddd YY/MM/Do",
    "ddd YY/MM/DD",
    "ddd YY/MMM/D",
    "ddd YY/MMM/Do",
    "ddd YY/MMM/DD",
    "ddd YY/MMMM/D",
    "ddd YY/MMMM/Do",
    "ddd YY/MMMM/DD",
    "ddd YYYY/M/D",
    "ddd YYYY/M/Do",
    "ddd YYYY/M/DD",
    "ddd YYYY/Mo/D",
    "ddd YYYY/Mo/Do",
    "ddd YYYY/Mo/DD",
    "ddd YYYY/MM/D",
    "ddd YYYY/MM/Do",
    "ddd YYYY/MM/DD",
    "ddd YYYY/MMM/D",
    "ddd YYYY/MMM/Do",
    "ddd YYYY/MMM/DD",
    "ddd YYYY/MMMM/D",
    "ddd YYYY/MMMM/Do",
    "ddd YYYY/MMMM/DD",
    "ddd YY/D/M",
    "ddd YY/D/Mo",
    "ddd YY/D/MM",
    "ddd YY/D/MMM",
    "ddd YY/D/MMMM",
    "ddd YY/Do/M",
    "ddd YY/Do/Mo",
    "ddd YY/Do/MM",
    "ddd YY/Do/MMM",
    "ddd YY/Do/MMMM",
    "ddd YY/DD/M",
    "ddd YY/DD/Mo",
    "ddd YY/DD/MM",
    "ddd YY/DD/MMM",
    "ddd YY/DD/MMMM",
    "ddd YYYY/D/M",
    "ddd YYYY/D/Mo",
    "ddd YYYY/D/MM",
    "ddd YYYY/D/MMM",
    "ddd YYYY/D/MMMM",
    "ddd YYYY/Do/M",
    "ddd YYYY/Do/Mo",
    "ddd YYYY/Do/MM",
    "ddd YYYY/Do/MMM",
    "ddd YYYY/Do/MMMM",
    "ddd YYYY/DD/M",
    "ddd YYYY/DD/Mo",
    "ddd YYYY/DD/MM",
    "ddd YYYY/DD/MMM",
    "ddd YYYY/DD/MMMM",
    "ddd D.M",
    "ddd D.Mo",
    "ddd D.MM",
    "ddd D.MMM",
    "ddd D.MMMM",
    "ddd Do.M",
    "ddd Do.Mo",
    "ddd Do.MM",
    "ddd Do.MMM",
    "ddd Do.MMMM",
    "ddd DD.M",
    "ddd DD.Mo",
    "ddd DD.MM",
    "ddd DD.MMM",
    "ddd DD.MMMM",
    "ddd M.YY",
    "ddd M.YYYY",
    "ddd Mo.YY",
    "ddd Mo.YYYY",
    "ddd MM.YY",
    "ddd MM.YYYY",
    "ddd MMM.YY",
    "ddd MMM.YYYY",
    "ddd MMMM.YY",
    "ddd MMMM.YYYY",
    "ddd D.M.YY",
    "ddd D.M.YYYY",
    "ddd D.Mo.YY",
    "ddd D.Mo.YYYY",
    "ddd D.MM.YY",
    "ddd D.MM.YYYY",
    "ddd D.MMM.YY",
    "ddd D.MMM.YYYY",
    "ddd D.MMMM.YY",
    "ddd D.MMMM.YYYY",
    "ddd Do.M.YY",
    "ddd Do.M.YYYY",
    "ddd Do.Mo.YY",
    "ddd Do.Mo.YYYY",
    "ddd Do.MM.YY",
    "ddd Do.MM.YYYY",
    "ddd Do.MMM.YY",
    "ddd Do.MMM.YYYY",
    "ddd Do.MMMM.YY",
    "ddd Do.MMMM.YYYY",
    "ddd DD.M.YY",
    "ddd DD.M.YYYY",
    "ddd DD.Mo.YY",
    "ddd DD.Mo.YYYY",
    "ddd DD.MM.YY",
    "ddd DD.MM.YYYY",
    "ddd DD.MMM.YY",
    "ddd DD.MMM.YYYY",
    "ddd DD.MMMM.YY",
    "ddd DD.MMMM.YYYY",
    "ddd M.D.YY",
    "ddd M.D.YYYY",
    "ddd M.Do.YY",
    "ddd M.Do.YYYY",
    "ddd M.DD.YY",
    "ddd M.DD.YYYY",
    "ddd Mo.D.YY",
    "ddd Mo.D.YYYY",
    "ddd Mo.Do.YY",
    "ddd Mo.Do.YYYY",
    "ddd Mo.DD.YY",
    "ddd Mo.DD.YYYY",
    "ddd MM.D.YY",
    "ddd MM.D.YYYY",
    "ddd MM.Do.YY",
    "ddd MM.Do.YYYY",
    "ddd MM.DD.YY",
    "ddd MM.DD.YYYY",
    "ddd MMM.D.YY",
    "ddd MMM.D.YYYY",
    "ddd MMM.Do.YY",
    "ddd MMM.Do.YYYY",
    "ddd MMM.DD.YY",
    "ddd MMM.DD.YYYY",
    "ddd MMMM.D.YY",
    "ddd MMMM.D.YYYY",
    "ddd MMMM.Do.YY",
    "ddd MMMM.Do.YYYY",
    "ddd MMMM.DD.YY",
    "ddd MMMM.DD.YYYY",
    "ddd M.D",
    "ddd M.Do",
    "ddd M.DD",
    "ddd Mo.D",
    "ddd Mo.Do",
    "ddd Mo.DD",
    "ddd MM.D",
    "ddd MM.Do",
    "ddd MM.DD",
    "ddd MMM.D",
    "ddd MMM.Do",
    "ddd MMM.DD",
    "ddd MMMM.D",
    "ddd MMMM.Do",
    "ddd MMMM.DD",
    "ddd YY.M",
    "ddd YY.Mo",
    "ddd YY.MM",
    "ddd YY.MMM",
    "ddd YY.MMMM",
    "ddd YYYY.M",
    "ddd YYYY.Mo",
    "ddd YYYY.MM",
    "ddd YYYY.MMM",
    "ddd YYYY.MMMM",
    "ddd YY.M.D",
    "ddd YY.M.Do",
    "ddd YY.M.DD",
    "ddd YY.Mo.D",
    "ddd YY.Mo.Do",
    "ddd YY.Mo.DD",
    "ddd YY.MM.D",
    "ddd YY.MM.Do",
    "ddd YY.MM.DD",
    "ddd YY.MMM.D",
    "ddd YY.MMM.Do",
    "ddd YY.MMM.DD",
    "ddd YY.MMMM.D",
    "ddd YY.MMMM.Do",
    "ddd YY.MMMM.DD",
    "ddd YYYY.M.D",
    "ddd YYYY.M.Do",
    "ddd YYYY.M.DD",
    "ddd YYYY.Mo.D",
    "ddd YYYY.Mo.Do",
    "ddd YYYY.Mo.DD",
    "ddd YYYY.MM.D",
    "ddd YYYY.MM.Do",
    "ddd YYYY.MM.DD",
    "ddd YYYY.MMM.D",
    "ddd YYYY.MMM.Do",
    "ddd YYYY.MMM.DD",
    "ddd YYYY.MMMM.D",
    "ddd YYYY.MMMM.Do",
    "ddd YYYY.MMMM.DD",
    "ddd YY.D.M",
    "ddd YY.D.Mo",
    "ddd YY.D.MM",
    "ddd YY.D.MMM",
    "ddd YY.D.MMMM",
    "ddd YY.Do.M",
    "ddd YY.Do.Mo",
    "ddd YY.Do.MM",
    "ddd YY.Do.MMM",
    "ddd YY.Do.MMMM",
    "ddd YY.DD.M",
    "ddd YY.DD.Mo",
    "ddd YY.DD.MM",
    "ddd YY.DD.MMM",
    "ddd YY.DD.MMMM",
    "ddd YYYY.D.M",
    "ddd YYYY.D.Mo",
    "ddd YYYY.D.MM",
    "ddd YYYY.D.MMM",
    "ddd YYYY.D.MMMM",
    "ddd YYYY.Do.M",
    "ddd YYYY.Do.Mo",
    "ddd YYYY.Do.MM",
    "ddd YYYY.Do.MMM",
    "ddd YYYY.Do.MMMM",
    "ddd YYYY.DD.M",
    "ddd YYYY.DD.Mo",
    "ddd YYYY.DD.MM",
    "ddd YYYY.DD.MMM",
    "ddd YYYY.DD.MMMM",
    "ddd D M",
    "ddd D Mo",
    "ddd D MM",
    "ddd D MMM",
    "ddd D MMMM",
    "ddd Do M",
    "ddd Do Mo",
    "ddd Do MM",
    "ddd Do MMM",
    "ddd Do MMMM",
    "ddd DD M",
    "ddd DD Mo",
    "ddd DD MM",
    "ddd DD MMM",
    "ddd DD MMMM",
    "ddd M YY",
    "ddd M YYYY",
    "ddd Mo YY",
    "ddd Mo YYYY",
    "ddd MM YY",
    "ddd MM YYYY",
    "ddd MMM YY",
    "ddd MMM YYYY",
    "ddd MMMM YY",
    "ddd MMMM YYYY",
    "ddd D M YY",
    "ddd D M YYYY",
    "ddd D Mo YY",
    "ddd D Mo YYYY",
    "ddd D MM YY",
    "ddd D MM YYYY",
    "ddd D MMM YY",
    "ddd D MMM YYYY",
    "ddd D MMMM YY",
    "ddd D MMMM YYYY",
    "ddd Do M YY",
    "ddd Do M YYYY",
    "ddd Do Mo YY",
    "ddd Do Mo YYYY",
    "ddd Do MM YY",
    "ddd Do MM YYYY",
    "ddd Do MMM YY",
    "ddd Do MMM YYYY",
    "ddd Do MMMM YY",
    "ddd Do MMMM YYYY",
    "ddd DD M YY",
    "ddd DD M YYYY",
    "ddd DD Mo YY",
    "ddd DD Mo YYYY",
    "ddd DD MM YY",
    "ddd DD MM YYYY",
    "ddd DD MMM YY",
    "ddd DD MMM YYYY",
    "ddd DD MMMM YY",
    "ddd DD MMMM YYYY",
    "ddd M D YY",
    "ddd M D YYYY",
    "ddd M Do YY",
    "ddd M Do YYYY",
    "ddd M DD YY",
    "ddd M DD YYYY",
    "ddd Mo D YY",
    "ddd Mo D YYYY",
    "ddd Mo Do YY",
    "ddd Mo Do YYYY",
    "ddd Mo DD YY",
    "ddd Mo DD YYYY",
    "ddd MM D YY",
    "ddd MM D YYYY",
    "ddd MM Do YY",
    "ddd MM Do YYYY",
    "ddd MM DD YY",
    "ddd MM DD YYYY",
    "ddd MMM D YY",
    "ddd MMM D YYYY",
    "ddd MMM Do YY",
    "ddd MMM Do YYYY",
    "ddd MMM DD YY",
    "ddd MMM DD YYYY",
    "ddd MMMM D YY",
    "ddd MMMM D YYYY",
    "ddd MMMM Do YY",
    "ddd MMMM Do YYYY",
    "ddd MMMM DD YY",
    "ddd MMMM DD YYYY",
    "ddd M D",
    "ddd M Do",
    "ddd M DD",
    "ddd Mo D",
    "ddd Mo Do",
    "ddd Mo DD",
    "ddd MM D",
    "ddd MM Do",
    "ddd MM DD",
    "ddd MMM D",
    "ddd MMM Do",
    "ddd MMM DD",
    "ddd MMMM D",
    "ddd MMMM Do",
    "ddd MMMM DD",
    "ddd YY M",
    "ddd YY Mo",
    "ddd YY MM",
    "ddd YY MMM",
    "ddd YY MMMM",
    "ddd YYYY M",
    "ddd YYYY Mo",
    "ddd YYYY MM",
    "ddd YYYY MMM",
    "ddd YYYY MMMM",
    "ddd YY M D",
    "ddd YY M Do",
    "ddd YY M DD",
    "ddd YY Mo D",
    "ddd YY Mo Do",
    "ddd YY Mo DD",
    "ddd YY MM D",
    "ddd YY MM Do",
    "ddd YY MM DD",
    "ddd YY MMM D",
    "ddd YY MMM Do",
    "ddd YY MMM DD",
    "ddd YY MMMM D",
    "ddd YY MMMM Do",
    "ddd YY MMMM DD",
    "ddd YYYY M D",
    "ddd YYYY M Do",
    "ddd YYYY M DD",
    "ddd YYYY Mo D",
    "ddd YYYY Mo Do",
    "ddd YYYY Mo DD",
    "ddd YYYY MM D",
    "ddd YYYY MM Do",
    "ddd YYYY MM DD",
    "ddd YYYY MMM D",
    "ddd YYYY MMM Do",
    "ddd YYYY MMM DD",
    "ddd YYYY MMMM D",
    "ddd YYYY MMMM Do",
    "ddd YYYY MMMM DD",
    "ddd YY D M",
    "ddd YY D Mo",
    "ddd YY D MM",
    "ddd YY D MMM",
    "ddd YY D MMMM",
    "ddd YY Do M",
    "ddd YY Do Mo",
    "ddd YY Do MM",
    "ddd YY Do MMM",
    "ddd YY Do MMMM",
    "ddd YY DD M",
    "ddd YY DD Mo",
    "ddd YY DD MM",
    "ddd YY DD MMM",
    "ddd YY DD MMMM",
    "ddd YYYY D M",
    "ddd YYYY D Mo",
    "ddd YYYY D MM",
    "ddd YYYY D MMM",
    "ddd YYYY D MMMM",
    "ddd YYYY Do M",
    "ddd YYYY Do Mo",
    "ddd YYYY Do MM",
    "ddd YYYY Do MMM",
    "ddd YYYY Do MMMM",
    "ddd YYYY DD M",
    "ddd YYYY DD Mo",
    "ddd YYYY DD MM",
    "ddd YYYY DD MMM",
    "ddd YYYY DD MMMM",
    "ddd DM",
    "ddd DMo",
    "ddd DMM",
    "ddd DMMM",
    "ddd DMMMM",
    "ddd DoM",
    "ddd DoMo",
    "ddd DoMM",
    "ddd DoMMM",
    "ddd DoMMMM",
    "ddd DDM",
    "ddd DDMo",
    "ddd DDMM",
    "ddd DDMMM",
    "ddd DDMMMM",
    "ddd MYY",
    "ddd MYYYY",
    "ddd MoYY",
    "ddd MoYYYY",
    "ddd MMYY",
    "ddd MMYYYY",
    "ddd MMMYY",
    "ddd MMMYYYY",
    "ddd MMMMYY",
    "ddd MMMMYYYY",
    "ddd DMYY",
    "ddd DMYYYY",
    "ddd DMoYY",
    "ddd DMoYYYY",
    "ddd DMMYY",
    "ddd DMMYYYY",
    "ddd DMMMYY",
    "ddd DMMMYYYY",
    "ddd DMMMMYY",
    "ddd DMMMMYYYY",
    "ddd DoMYY",
    "ddd DoMYYYY",
    "ddd DoMoYY",
    "ddd DoMoYYYY",
    "ddd DoMMYY",
    "ddd DoMMYYYY",
    "ddd DoMMMYY",
    "ddd DoMMMYYYY",
    "ddd DoMMMMYY",
    "ddd DoMMMMYYYY",
    "ddd DDMYY",
    "ddd DDMYYYY",
    "ddd DDMoYY",
    "ddd DDMoYYYY",
    "ddd DDMMYY",
    "ddd DDMMYYYY",
    "ddd DDMMMYY",
    "ddd DDMMMYYYY",
    "ddd DDMMMMYY",
    "ddd DDMMMMYYYY",
    "ddd MDYY",
    "ddd MDYYYY",
    "ddd MDoYY",
    "ddd MDoYYYY",
    "ddd MDDYY",
    "ddd MDDYYYY",
    "ddd MoDYY",
    "ddd MoDYYYY",
    "ddd MoDoYY",
    "ddd MoDoYYYY",
    "ddd MoDDYY",
    "ddd MoDDYYYY",
    "ddd MMDYY",
    "ddd MMDYYYY",
    "ddd MMDoYY",
    "ddd MMDoYYYY",
    "ddd MMDDYY",
    "ddd MMDDYYYY",
    "ddd MMMDYY",
    "ddd MMMDYYYY",
    "ddd MMMDoYY",
    "ddd MMMDoYYYY",
    "ddd MMMDDYY",
    "ddd MMMDDYYYY",
    "ddd MMMMDYY",
    "ddd MMMMDYYYY",
    "ddd MMMMDoYY",
    "ddd MMMMDoYYYY",
    "ddd MMMMDDYY",
    "ddd MMMMDDYYYY",
    "ddd MD",
    "ddd MDo",
    "ddd MDD",
    "ddd MoD",
    "ddd MoDo",
    "ddd MoDD",
    "ddd MMD",
    "ddd MMDo",
    "ddd MMDD",
    "ddd MMMD",
    "ddd MMMDo",
    "ddd MMMDD",
    "ddd MMMMD",
    "ddd MMMMDo",
    "ddd MMMMDD",
    "ddd YYM",
    "ddd YYMo",
    "ddd YYMM",
    "ddd YYMMM",
    "ddd YYMMMM",
    "ddd YYYYM",
    "ddd YYYYMo",
    "ddd YYYYMM",
    "ddd YYYYMMM",
    "ddd YYYYMMMM",
    "ddd YYMD",
    "ddd YYMDo",
    "ddd YYMDD",
    "ddd YYMoD",
    "ddd YYMoDo",
    "ddd YYMoDD",
    "ddd YYMMD",
    "ddd YYMMDo",
    "ddd YYMMDD",
    "ddd YYMMMD",
    "ddd YYMMMDo",
    "ddd YYMMMDD",
    "ddd YYMMMMD",
    "ddd YYMMMMDo",
    "ddd YYMMMMDD",
    "ddd YYYYMD",
    "ddd YYYYMDo",
    "ddd YYYYMDD",
    "ddd YYYYMoD",
    "ddd YYYYMoDo",
    "ddd YYYYMoDD",
    "ddd YYYYMMD",
    "ddd YYYYMMDo",
    "ddd YYYYMMDD",
    "ddd YYYYMMMD",
    "ddd YYYYMMMDo",
    "ddd YYYYMMMDD",
    "ddd YYYYMMMMD",
    "ddd YYYYMMMMDo",
    "ddd YYYYMMMMDD",
    "ddd YYDM",
    "ddd YYDMo",
    "ddd YYDMM",
    "ddd YYDMMM",
    "ddd YYDMMMM",
    "ddd YYDoM",
    "ddd YYDoMo",
    "ddd YYDoMM",
    "ddd YYDoMMM",
    "ddd YYDoMMMM",
    "ddd YYDDM",
    "ddd YYDDMo",
    "ddd YYDDMM",
    "ddd YYDDMMM",
    "ddd YYDDMMMM",
    "ddd YYYYDM",
    "ddd YYYYDMo",
    "ddd YYYYDMM",
    "ddd YYYYDMMM",
    "ddd YYYYDMMMM",
    "ddd YYYYDoM",
    "ddd YYYYDoMo",
    "ddd YYYYDoMM",
    "ddd YYYYDoMMM",
    "ddd YYYYDoMMMM",
    "ddd YYYYDDM",
    "ddd YYYYDDMo",
    "ddd YYYYDDMM",
    "ddd YYYYDDMMM",
    "ddd YYYYDDMMMM",
    "ddd M Do, YY",
    "ddd M Do, YYYY",
    "ddd Mo Do, YY",
    "ddd Mo Do, YYYY",
    "ddd MM Do, YY",
    "ddd MM Do, YYYY",
    "ddd MMM Do, YY",
    "ddd MMM Do, YYYY",
    "ddd MMMM Do, YY",
    "ddd MMMM Do, YYYY",
    "ddd M D, YY",
    "ddd M D, YYYY",
    "ddd Mo D, YY",
    "ddd Mo D, YYYY",
    "ddd MM D, YY",
    "ddd MM D, YYYY",
    "ddd MMM D, YY",
    "ddd MMM D, YYYY",
    "ddd MMMM D, YY",
    "ddd MMMM D, YYYY",
    "ddd M DD, YY",
    "ddd M DD, YYYY",
    "ddd Mo DD, YY",
    "ddd Mo DD, YYYY",
    "ddd MM DD, YY",
    "ddd MM DD, YYYY",
    "ddd MMM DD, YY",
    "ddd MMM DD, YYYY",
    "ddd MMMM DD, YY",
    "ddd MMMM DD, YYYY",
    "dddd D-M",
    "dddd D-Mo",
    "dddd D-MM",
    "dddd D-MMM",
    "dddd D-MMMM",
    "dddd Do-M",
    "dddd Do-Mo",
    "dddd Do-MM",
    "dddd Do-MMM",
    "dddd Do-MMMM",
    "dddd DD-M",
    "dddd DD-Mo",
    "dddd DD-MM",
    "dddd DD-MMM",
    "dddd DD-MMMM",
    "dddd M-YY",
    "dddd M-YYYY",
    "dddd Mo-YY",
    "dddd Mo-YYYY",
    "dddd MM-YY",
    "dddd MM-YYYY",
    "dddd MMM-YY",
    "dddd MMM-YYYY",
    "dddd MMMM-YY",
    "dddd MMMM-YYYY",
    "dddd D-M-YY",
    "dddd D-M-YYYY",
    "dddd D-Mo-YY",
    "dddd D-Mo-YYYY",
    "dddd D-MM-YY",
    "dddd D-MM-YYYY",
    "dddd D-MMM-YY",
    "dddd D-MMM-YYYY",
    "dddd D-MMMM-YY",
    "dddd D-MMMM-YYYY",
    "dddd Do-M-YY",
    "dddd Do-M-YYYY",
    "dddd Do-Mo-YY",
    "dddd Do-Mo-YYYY",
    "dddd Do-MM-YY",
    "dddd Do-MM-YYYY",
    "dddd Do-MMM-YY",
    "dddd Do-MMM-YYYY",
    "dddd Do-MMMM-YY",
    "dddd Do-MMMM-YYYY",
    "dddd DD-M-YY",
    "dddd DD-M-YYYY",
    "dddd DD-Mo-YY",
    "dddd DD-Mo-YYYY",
    "dddd DD-MM-YY",
    "dddd DD-MM-YYYY",
    "dddd DD-MMM-YY",
    "dddd DD-MMM-YYYY",
    "dddd DD-MMMM-YY",
    "dddd DD-MMMM-YYYY",
    "dddd M-D-YY",
    "dddd M-D-YYYY",
    "dddd M-Do-YY",
    "dddd M-Do-YYYY",
    "dddd M-DD-YY",
    "dddd M-DD-YYYY",
    "dddd Mo-D-YY",
    "dddd Mo-D-YYYY",
    "dddd Mo-Do-YY",
    "dddd Mo-Do-YYYY",
    "dddd Mo-DD-YY",
    "dddd Mo-DD-YYYY",
    "dddd MM-D-YY",
    "dddd MM-D-YYYY",
    "dddd MM-Do-YY",
    "dddd MM-Do-YYYY",
    "dddd MM-DD-YY",
    "dddd MM-DD-YYYY",
    "dddd MMM-D-YY",
    "dddd MMM-D-YYYY",
    "dddd MMM-Do-YY",
    "dddd MMM-Do-YYYY",
    "dddd MMM-DD-YY",
    "dddd MMM-DD-YYYY",
    "dddd MMMM-D-YY",
    "dddd MMMM-D-YYYY",
    "dddd MMMM-Do-YY",
    "dddd MMMM-Do-YYYY",
    "dddd MMMM-DD-YY",
    "dddd MMMM-DD-YYYY",
    "dddd M-D",
    "dddd M-Do",
    "dddd M-DD",
    "dddd Mo-D",
    "dddd Mo-Do",
    "dddd Mo-DD",
    "dddd MM-D",
    "dddd MM-Do",
    "dddd MM-DD",
    "dddd MMM-D",
    "dddd MMM-Do",
    "dddd MMM-DD",
    "dddd MMMM-D",
    "dddd MMMM-Do",
    "dddd MMMM-DD",
    "dddd YY-M",
    "dddd YY-Mo",
    "dddd YY-MM",
    "dddd YY-MMM",
    "dddd YY-MMMM",
    "dddd YYYY-M",
    "dddd YYYY-Mo",
    "dddd YYYY-MM",
    "dddd YYYY-MMM",
    "dddd YYYY-MMMM",
    "dddd YY-M-D",
    "dddd YY-M-Do",
    "dddd YY-M-DD",
    "dddd YY-Mo-D",
    "dddd YY-Mo-Do",
    "dddd YY-Mo-DD",
    "dddd YY-MM-D",
    "dddd YY-MM-Do",
    "dddd YY-MM-DD",
    "dddd YY-MMM-D",
    "dddd YY-MMM-Do",
    "dddd YY-MMM-DD",
    "dddd YY-MMMM-D",
    "dddd YY-MMMM-Do",
    "dddd YY-MMMM-DD",
    "dddd YYYY-M-D",
    "dddd YYYY-M-Do",
    "dddd YYYY-M-DD",
    "dddd YYYY-Mo-D",
    "dddd YYYY-Mo-Do",
    "dddd YYYY-Mo-DD",
    "dddd YYYY-MM-D",
    "dddd YYYY-MM-Do",
    "dddd YYYY-MM-DD",
    "dddd YYYY-MMM-D",
    "dddd YYYY-MMM-Do",
    "dddd YYYY-MMM-DD",
    "dddd YYYY-MMMM-D",
    "dddd YYYY-MMMM-Do",
    "dddd YYYY-MMMM-DD",
    "dddd YY-D-M",
    "dddd YY-D-Mo",
    "dddd YY-D-MM",
    "dddd YY-D-MMM",
    "dddd YY-D-MMMM",
    "dddd YY-Do-M",
    "dddd YY-Do-Mo",
    "dddd YY-Do-MM",
    "dddd YY-Do-MMM",
    "dddd YY-Do-MMMM",
    "dddd YY-DD-M",
    "dddd YY-DD-Mo",
    "dddd YY-DD-MM",
    "dddd YY-DD-MMM",
    "dddd YY-DD-MMMM",
    "dddd YYYY-D-M",
    "dddd YYYY-D-Mo",
    "dddd YYYY-D-MM",
    "dddd YYYY-D-MMM",
    "dddd YYYY-D-MMMM",
    "dddd YYYY-Do-M",
    "dddd YYYY-Do-Mo",
    "dddd YYYY-Do-MM",
    "dddd YYYY-Do-MMM",
    "dddd YYYY-Do-MMMM",
    "dddd YYYY-DD-M",
    "dddd YYYY-DD-Mo",
    "dddd YYYY-DD-MM",
    "dddd YYYY-DD-MMM",
    "dddd YYYY-DD-MMMM",
    "dddd D/M",
    "dddd D/Mo",
    "dddd D/MM",
    "dddd D/MMM",
    "dddd D/MMMM",
    "dddd Do/M",
    "dddd Do/Mo",
    "dddd Do/MM",
    "dddd Do/MMM",
    "dddd Do/MMMM",
    "dddd DD/M",
    "dddd DD/Mo",
    "dddd DD/MM",
    "dddd DD/MMM",
    "dddd DD/MMMM",
    "dddd M/YY",
    "dddd M/YYYY",
    "dddd Mo/YY",
    "dddd Mo/YYYY",
    "dddd MM/YY",
    "dddd MM/YYYY",
    "dddd MMM/YY",
    "dddd MMM/YYYY",
    "dddd MMMM/YY",
    "dddd MMMM/YYYY",
    "dddd D/M/YY",
    "dddd D/M/YYYY",
    "dddd D/Mo/YY",
    "dddd D/Mo/YYYY",
    "dddd D/MM/YY",
    "dddd D/MM/YYYY",
    "dddd D/MMM/YY",
    "dddd D/MMM/YYYY",
    "dddd D/MMMM/YY",
    "dddd D/MMMM/YYYY",
    "dddd Do/M/YY",
    "dddd Do/M/YYYY",
    "dddd Do/Mo/YY",
    "dddd Do/Mo/YYYY",
    "dddd Do/MM/YY",
    "dddd Do/MM/YYYY",
    "dddd Do/MMM/YY",
    "dddd Do/MMM/YYYY",
    "dddd Do/MMMM/YY",
    "dddd Do/MMMM/YYYY",
    "dddd DD/M/YY",
    "dddd DD/M/YYYY",
    "dddd DD/Mo/YY",
    "dddd DD/Mo/YYYY",
    "dddd DD/MM/YY",
    "dddd DD/MM/YYYY",
    "dddd DD/MMM/YY",
    "dddd DD/MMM/YYYY",
    "dddd DD/MMMM/YY",
    "dddd DD/MMMM/YYYY",
    "dddd M/D/YY",
    "dddd M/D/YYYY",
    "dddd M/Do/YY",
    "dddd M/Do/YYYY",
    "dddd M/DD/YY",
    "dddd M/DD/YYYY",
    "dddd Mo/D/YY",
    "dddd Mo/D/YYYY",
    "dddd Mo/Do/YY",
    "dddd Mo/Do/YYYY",
    "dddd Mo/DD/YY",
    "dddd Mo/DD/YYYY",
    "dddd MM/D/YY",
    "dddd MM/D/YYYY",
    "dddd MM/Do/YY",
    "dddd MM/Do/YYYY",
    "dddd MM/DD/YY",
    "dddd MM/DD/YYYY",
    "dddd MMM/D/YY",
    "dddd MMM/D/YYYY",
    "dddd MMM/Do/YY",
    "dddd MMM/Do/YYYY",
    "dddd MMM/DD/YY",
    "dddd MMM/DD/YYYY",
    "dddd MMMM/D/YY",
    "dddd MMMM/D/YYYY",
    "dddd MMMM/Do/YY",
    "dddd MMMM/Do/YYYY",
    "dddd MMMM/DD/YY",
    "dddd MMMM/DD/YYYY",
    "dddd M/D",
    "dddd M/Do",
    "dddd M/DD",
    "dddd Mo/D",
    "dddd Mo/Do",
    "dddd Mo/DD",
    "dddd MM/D",
    "dddd MM/Do",
    "dddd MM/DD",
    "dddd MMM/D",
    "dddd MMM/Do",
    "dddd MMM/DD",
    "dddd MMMM/D",
    "dddd MMMM/Do",
    "dddd MMMM/DD",
    "dddd YY/M",
    "dddd YY/Mo",
    "dddd YY/MM",
    "dddd YY/MMM",
    "dddd YY/MMMM",
    "dddd YYYY/M",
    "dddd YYYY/Mo",
    "dddd YYYY/MM",
    "dddd YYYY/MMM",
    "dddd YYYY/MMMM",
    "dddd YY/M/D",
    "dddd YY/M/Do",
    "dddd YY/M/DD",
    "dddd YY/Mo/D",
    "dddd YY/Mo/Do",
    "dddd YY/Mo/DD",
    "dddd YY/MM/D",
    "dddd YY/MM/Do",
    "dddd YY/MM/DD",
    "dddd YY/MMM/D",
    "dddd YY/MMM/Do",
    "dddd YY/MMM/DD",
    "dddd YY/MMMM/D",
    "dddd YY/MMMM/Do",
    "dddd YY/MMMM/DD",
    "dddd YYYY/M/D",
    "dddd YYYY/M/Do",
    "dddd YYYY/M/DD",
    "dddd YYYY/Mo/D",
    "dddd YYYY/Mo/Do",
    "dddd YYYY/Mo/DD",
    "dddd YYYY/MM/D",
    "dddd YYYY/MM/Do",
    "dddd YYYY/MM/DD",
    "dddd YYYY/MMM/D",
    "dddd YYYY/MMM/Do",
    "dddd YYYY/MMM/DD",
    "dddd YYYY/MMMM/D",
    "dddd YYYY/MMMM/Do",
    "dddd YYYY/MMMM/DD",
    "dddd YY/D/M",
    "dddd YY/D/Mo",
    "dddd YY/D/MM",
    "dddd YY/D/MMM",
    "dddd YY/D/MMMM",
    "dddd YY/Do/M",
    "dddd YY/Do/Mo",
    "dddd YY/Do/MM",
    "dddd YY/Do/MMM",
    "dddd YY/Do/MMMM",
    "dddd YY/DD/M",
    "dddd YY/DD/Mo",
    "dddd YY/DD/MM",
    "dddd YY/DD/MMM",
    "dddd YY/DD/MMMM",
    "dddd YYYY/D/M",
    "dddd YYYY/D/Mo",
    "dddd YYYY/D/MM",
    "dddd YYYY/D/MMM",
    "dddd YYYY/D/MMMM",
    "dddd YYYY/Do/M",
    "dddd YYYY/Do/Mo",
    "dddd YYYY/Do/MM",
    "dddd YYYY/Do/MMM",
    "dddd YYYY/Do/MMMM",
    "dddd YYYY/DD/M",
    "dddd YYYY/DD/Mo",
    "dddd YYYY/DD/MM",
    "dddd YYYY/DD/MMM",
    "dddd YYYY/DD/MMMM",
    "dddd D.M",
    "dddd D.Mo",
    "dddd D.MM",
    "dddd D.MMM",
    "dddd D.MMMM",
    "dddd Do.M",
    "dddd Do.Mo",
    "dddd Do.MM",
    "dddd Do.MMM",
    "dddd Do.MMMM",
    "dddd DD.M",
    "dddd DD.Mo",
    "dddd DD.MM",
    "dddd DD.MMM",
    "dddd DD.MMMM",
    "dddd M.YY",
    "dddd M.YYYY",
    "dddd Mo.YY",
    "dddd Mo.YYYY",
    "dddd MM.YY",
    "dddd MM.YYYY",
    "dddd MMM.YY",
    "dddd MMM.YYYY",
    "dddd MMMM.YY",
    "dddd MMMM.YYYY",
    "dddd D.M.YY",
    "dddd D.M.YYYY",
    "dddd D.Mo.YY",
    "dddd D.Mo.YYYY",
    "dddd D.MM.YY",
    "dddd D.MM.YYYY",
    "dddd D.MMM.YY",
    "dddd D.MMM.YYYY",
    "dddd D.MMMM.YY",
    "dddd D.MMMM.YYYY",
    "dddd Do.M.YY",
    "dddd Do.M.YYYY",
    "dddd Do.Mo.YY",
    "dddd Do.Mo.YYYY",
    "dddd Do.MM.YY",
    "dddd Do.MM.YYYY",
    "dddd Do.MMM.YY",
    "dddd Do.MMM.YYYY",
    "dddd Do.MMMM.YY",
    "dddd Do.MMMM.YYYY",
    "dddd DD.M.YY",
    "dddd DD.M.YYYY",
    "dddd DD.Mo.YY",
    "dddd DD.Mo.YYYY",
    "dddd DD.MM.YY",
    "dddd DD.MM.YYYY",
    "dddd DD.MMM.YY",
    "dddd DD.MMM.YYYY",
    "dddd DD.MMMM.YY",
    "dddd DD.MMMM.YYYY",
    "dddd M.D.YY",
    "dddd M.D.YYYY",
    "dddd M.Do.YY",
    "dddd M.Do.YYYY",
    "dddd M.DD.YY",
    "dddd M.DD.YYYY",
    "dddd Mo.D.YY",
    "dddd Mo.D.YYYY",
    "dddd Mo.Do.YY",
    "dddd Mo.Do.YYYY",
    "dddd Mo.DD.YY",
    "dddd Mo.DD.YYYY",
    "dddd MM.D.YY",
    "dddd MM.D.YYYY",
    "dddd MM.Do.YY",
    "dddd MM.Do.YYYY",
    "dddd MM.DD.YY",
    "dddd MM.DD.YYYY",
    "dddd MMM.D.YY",
    "dddd MMM.D.YYYY",
    "dddd MMM.Do.YY",
    "dddd MMM.Do.YYYY",
    "dddd MMM.DD.YY",
    "dddd MMM.DD.YYYY",
    "dddd MMMM.D.YY",
    "dddd MMMM.D.YYYY",
    "dddd MMMM.Do.YY",
    "dddd MMMM.Do.YYYY",
    "dddd MMMM.DD.YY",
    "dddd MMMM.DD.YYYY",
    "dddd M.D",
    "dddd M.Do",
    "dddd M.DD",
    "dddd Mo.D",
    "dddd Mo.Do",
    "dddd Mo.DD",
    "dddd MM.D",
    "dddd MM.Do",
    "dddd MM.DD",
    "dddd MMM.D",
    "dddd MMM.Do",
    "dddd MMM.DD",
    "dddd MMMM.D",
    "dddd MMMM.Do",
    "dddd MMMM.DD",
    "dddd YY.M",
    "dddd YY.Mo",
    "dddd YY.MM",
    "dddd YY.MMM",
    "dddd YY.MMMM",
    "dddd YYYY.M",
    "dddd YYYY.Mo",
    "dddd YYYY.MM",
    "dddd YYYY.MMM",
    "dddd YYYY.MMMM",
    "dddd YY.M.D",
    "dddd YY.M.Do",
    "dddd YY.M.DD",
    "dddd YY.Mo.D",
    "dddd YY.Mo.Do",
    "dddd YY.Mo.DD",
    "dddd YY.MM.D",
    "dddd YY.MM.Do",
    "dddd YY.MM.DD",
    "dddd YY.MMM.D",
    "dddd YY.MMM.Do",
    "dddd YY.MMM.DD",
    "dddd YY.MMMM.D",
    "dddd YY.MMMM.Do",
    "dddd YY.MMMM.DD",
    "dddd YYYY.M.D",
    "dddd YYYY.M.Do",
    "dddd YYYY.M.DD",
    "dddd YYYY.Mo.D",
    "dddd YYYY.Mo.Do",
    "dddd YYYY.Mo.DD",
    "dddd YYYY.MM.D",
    "dddd YYYY.MM.Do",
    "dddd YYYY.MM.DD",
    "dddd YYYY.MMM.D",
    "dddd YYYY.MMM.Do",
    "dddd YYYY.MMM.DD",
    "dddd YYYY.MMMM.D",
    "dddd YYYY.MMMM.Do",
    "dddd YYYY.MMMM.DD",
    "dddd YY.D.M",
    "dddd YY.D.Mo",
    "dddd YY.D.MM",
    "dddd YY.D.MMM",
    "dddd YY.D.MMMM",
    "dddd YY.Do.M",
    "dddd YY.Do.Mo",
    "dddd YY.Do.MM",
    "dddd YY.Do.MMM",
    "dddd YY.Do.MMMM",
    "dddd YY.DD.M",
    "dddd YY.DD.Mo",
    "dddd YY.DD.MM",
    "dddd YY.DD.MMM",
    "dddd YY.DD.MMMM",
    "dddd YYYY.D.M",
    "dddd YYYY.D.Mo",
    "dddd YYYY.D.MM",
    "dddd YYYY.D.MMM",
    "dddd YYYY.D.MMMM",
    "dddd YYYY.Do.M",
    "dddd YYYY.Do.Mo",
    "dddd YYYY.Do.MM",
    "dddd YYYY.Do.MMM",
    "dddd YYYY.Do.MMMM",
    "dddd YYYY.DD.M",
    "dddd YYYY.DD.Mo",
    "dddd YYYY.DD.MM",
    "dddd YYYY.DD.MMM",
    "dddd YYYY.DD.MMMM",
    "dddd D M",
    "dddd D Mo",
    "dddd D MM",
    "dddd D MMM",
    "dddd D MMMM",
    "dddd Do M",
    "dddd Do Mo",
    "dddd Do MM",
    "dddd Do MMM",
    "dddd Do MMMM",
    "dddd DD M",
    "dddd DD Mo",
    "dddd DD MM",
    "dddd DD MMM",
    "dddd DD MMMM",
    "dddd M YY",
    "dddd M YYYY",
    "dddd Mo YY",
    "dddd Mo YYYY",
    "dddd MM YY",
    "dddd MM YYYY",
    "dddd MMM YY",
    "dddd MMM YYYY",
    "dddd MMMM YY",
    "dddd MMMM YYYY",
    "dddd D M YY",
    "dddd D M YYYY",
    "dddd D Mo YY",
    "dddd D Mo YYYY",
    "dddd D MM YY",
    "dddd D MM YYYY",
    "dddd D MMM YY",
    "dddd D MMM YYYY",
    "dddd D MMMM YY",
    "dddd D MMMM YYYY",
    "dddd Do M YY",
    "dddd Do M YYYY",
    "dddd Do Mo YY",
    "dddd Do Mo YYYY",
    "dddd Do MM YY",
    "dddd Do MM YYYY",
    "dddd Do MMM YY",
    "dddd Do MMM YYYY",
    "dddd Do MMMM YY",
    "dddd Do MMMM YYYY",
    "dddd DD M YY",
    "dddd DD M YYYY",
    "dddd DD Mo YY",
    "dddd DD Mo YYYY",
    "dddd DD MM YY",
    "dddd DD MM YYYY",
    "dddd DD MMM YY",
    "dddd DD MMM YYYY",
    "dddd DD MMMM YY",
    "dddd DD MMMM YYYY",
    "dddd M D YY",
    "dddd M D YYYY",
    "dddd M Do YY",
    "dddd M Do YYYY",
    "dddd M DD YY",
    "dddd M DD YYYY",
    "dddd Mo D YY",
    "dddd Mo D YYYY",
    "dddd Mo Do YY",
    "dddd Mo Do YYYY",
    "dddd Mo DD YY",
    "dddd Mo DD YYYY",
    "dddd MM D YY",
    "dddd MM D YYYY",
    "dddd MM Do YY",
    "dddd MM Do YYYY",
    "dddd MM DD YY",
    "dddd MM DD YYYY",
    "dddd MMM D YY",
    "dddd MMM D YYYY",
    "dddd MMM Do YY",
    "dddd MMM Do YYYY",
    "dddd MMM DD YY",
    "dddd MMM DD YYYY",
    "dddd MMMM D YY",
    "dddd MMMM D YYYY",
    "dddd MMMM Do YY",
    "dddd MMMM Do YYYY",
    "dddd MMMM DD YY",
    "dddd MMMM DD YYYY",
    "dddd M D",
    "dddd M Do",
    "dddd M DD",
    "dddd Mo D",
    "dddd Mo Do",
    "dddd Mo DD",
    "dddd MM D",
    "dddd MM Do",
    "dddd MM DD",
    "dddd MMM D",
    "dddd MMM Do",
    "dddd MMM DD",
    "dddd MMMM D",
    "dddd MMMM Do",
    "dddd MMMM DD",
    "dddd YY M",
    "dddd YY Mo",
    "dddd YY MM",
    "dddd YY MMM",
    "dddd YY MMMM",
    "dddd YYYY M",
    "dddd YYYY Mo",
    "dddd YYYY MM",
    "dddd YYYY MMM",
    "dddd YYYY MMMM",
    "dddd YY M D",
    "dddd YY M Do",
    "dddd YY M DD",
    "dddd YY Mo D",
    "dddd YY Mo Do",
    "dddd YY Mo DD",
    "dddd YY MM D",
    "dddd YY MM Do",
    "dddd YY MM DD",
    "dddd YY MMM D",
    "dddd YY MMM Do",
    "dddd YY MMM DD",
    "dddd YY MMMM D",
    "dddd YY MMMM Do",
    "dddd YY MMMM DD",
    "dddd YYYY M D",
    "dddd YYYY M Do",
    "dddd YYYY M DD",
    "dddd YYYY Mo D",
    "dddd YYYY Mo Do",
    "dddd YYYY Mo DD",
    "dddd YYYY MM D",
    "dddd YYYY MM Do",
    "dddd YYYY MM DD",
    "dddd YYYY MMM D",
    "dddd YYYY MMM Do",
    "dddd YYYY MMM DD",
    "dddd YYYY MMMM D",
    "dddd YYYY MMMM Do",
    "dddd YYYY MMMM DD",
    "dddd YY D M",
    "dddd YY D Mo",
    "dddd YY D MM",
    "dddd YY D MMM",
    "dddd YY D MMMM",
    "dddd YY Do M",
    "dddd YY Do Mo",
    "dddd YY Do MM",
    "dddd YY Do MMM",
    "dddd YY Do MMMM",
    "dddd YY DD M",
    "dddd YY DD Mo",
    "dddd YY DD MM",
    "dddd YY DD MMM",
    "dddd YY DD MMMM",
    "dddd YYYY D M",
    "dddd YYYY D Mo",
    "dddd YYYY D MM",
    "dddd YYYY D MMM",
    "dddd YYYY D MMMM",
    "dddd YYYY Do M",
    "dddd YYYY Do Mo",
    "dddd YYYY Do MM",
    "dddd YYYY Do MMM",
    "dddd YYYY Do MMMM",
    "dddd YYYY DD M",
    "dddd YYYY DD Mo",
    "dddd YYYY DD MM",
    "dddd YYYY DD MMM",
    "dddd YYYY DD MMMM",
    "dddd DM",
    "dddd DMo",
    "dddd DMM",
    "dddd DMMM",
    "dddd DMMMM",
    "dddd DoM",
    "dddd DoMo",
    "dddd DoMM",
    "dddd DoMMM",
    "dddd DoMMMM",
    "dddd DDM",
    "dddd DDMo",
    "dddd DDMM",
    "dddd DDMMM",
    "dddd DDMMMM",
    "dddd MYY",
    "dddd MYYYY",
    "dddd MoYY",
    "dddd MoYYYY",
    "dddd MMYY",
    "dddd MMYYYY",
    "dddd MMMYY",
    "dddd MMMYYYY",
    "dddd MMMMYY",
    "dddd MMMMYYYY",
    "dddd DMYY",
    "dddd DMYYYY",
    "dddd DMoYY",
    "dddd DMoYYYY",
    "dddd DMMYY",
    "dddd DMMYYYY",
    "dddd DMMMYY",
    "dddd DMMMYYYY",
    "dddd DMMMMYY",
    "dddd DMMMMYYYY",
    "dddd DoMYY",
    "dddd DoMYYYY",
    "dddd DoMoYY",
    "dddd DoMoYYYY",
    "dddd DoMMYY",
    "dddd DoMMYYYY",
    "dddd DoMMMYY",
    "dddd DoMMMYYYY",
    "dddd DoMMMMYY",
    "dddd DoMMMMYYYY",
    "dddd DDMYY",
    "dddd DDMYYYY",
    "dddd DDMoYY",
    "dddd DDMoYYYY",
    "dddd DDMMYY",
    "dddd DDMMYYYY",
    "dddd DDMMMYY",
    "dddd DDMMMYYYY",
    "dddd DDMMMMYY",
    "dddd DDMMMMYYYY",
    "dddd MDYY",
    "dddd MDYYYY",
    "dddd MDoYY",
    "dddd MDoYYYY",
    "dddd MDDYY",
    "dddd MDDYYYY",
    "dddd MoDYY",
    "dddd MoDYYYY",
    "dddd MoDoYY",
    "dddd MoDoYYYY",
    "dddd MoDDYY",
    "dddd MoDDYYYY",
    "dddd MMDYY",
    "dddd MMDYYYY",
    "dddd MMDoYY",
    "dddd MMDoYYYY",
    "dddd MMDDYY",
    "dddd MMDDYYYY",
    "dddd MMMDYY",
    "dddd MMMDYYYY",
    "dddd MMMDoYY",
    "dddd MMMDoYYYY",
    "dddd MMMDDYY",
    "dddd MMMDDYYYY",
    "dddd MMMMDYY",
    "dddd MMMMDYYYY",
    "dddd MMMMDoYY",
    "dddd MMMMDoYYYY",
    "dddd MMMMDDYY",
    "dddd MMMMDDYYYY",
    "dddd MD",
    "dddd MDo",
    "dddd MDD",
    "dddd MoD",
    "dddd MoDo",
    "dddd MoDD",
    "dddd MMD",
    "dddd MMDo",
    "dddd MMDD",
    "dddd MMMD",
    "dddd MMMDo",
    "dddd MMMDD",
    "dddd MMMMD",
    "dddd MMMMDo",
    "dddd MMMMDD",
    "dddd YYM",
    "dddd YYMo",
    "dddd YYMM",
    "dddd YYMMM",
    "dddd YYMMMM",
    "dddd YYYYM",
    "dddd YYYYMo",
    "dddd YYYYMM",
    "dddd YYYYMMM",
    "dddd YYYYMMMM",
    "dddd YYMD",
    "dddd YYMDo",
    "dddd YYMDD",
    "dddd YYMoD",
    "dddd YYMoDo",
    "dddd YYMoDD",
    "dddd YYMMD",
    "dddd YYMMDo",
    "dddd YYMMDD",
    "dddd YYMMMD",
    "dddd YYMMMDo",
    "dddd YYMMMDD",
    "dddd YYMMMMD",
    "dddd YYMMMMDo",
    "dddd YYMMMMDD",
    "dddd YYYYMD",
    "dddd YYYYMDo",
    "dddd YYYYMDD",
    "dddd YYYYMoD",
    "dddd YYYYMoDo",
    "dddd YYYYMoDD",
    "dddd YYYYMMD",
    "dddd YYYYMMDo",
    "dddd YYYYMMDD",
    "dddd YYYYMMMD",
    "dddd YYYYMMMDo",
    "dddd YYYYMMMDD",
    "dddd YYYYMMMMD",
    "dddd YYYYMMMMDo",
    "dddd YYYYMMMMDD",
    "dddd YYDM",
    "dddd YYDMo",
    "dddd YYDMM",
    "dddd YYDMMM",
    "dddd YYDMMMM",
    "dddd YYDoM",
    "dddd YYDoMo",
    "dddd YYDoMM",
    "dddd YYDoMMM",
    "dddd YYDoMMMM",
    "dddd YYDDM",
    "dddd YYDDMo",
    "dddd YYDDMM",
    "dddd YYDDMMM",
    "dddd YYDDMMMM",
    "dddd YYYYDM",
    "dddd YYYYDMo",
    "dddd YYYYDMM",
    "dddd YYYYDMMM",
    "dddd YYYYDMMMM",
    "dddd YYYYDoM",
    "dddd YYYYDoMo",
    "dddd YYYYDoMM",
    "dddd YYYYDoMMM",
    "dddd YYYYDoMMMM",
    "dddd YYYYDDM",
    "dddd YYYYDDMo",
    "dddd YYYYDDMM",
    "dddd YYYYDDMMM",
    "dddd YYYYDDMMMM",
    "dddd M Do, YY",
    "dddd M Do, YYYY",
    "dddd Mo Do, YY",
    "dddd Mo Do, YYYY",
    "dddd MM Do, YY",
    "dddd MM Do, YYYY",
    "dddd MMM Do, YY",
    "dddd MMM Do, YYYY",
    "dddd MMMM Do, YY",
    "dddd MMMM Do, YYYY",
    "dddd M D, YY",
    "dddd M D, YYYY",
    "dddd Mo D, YY",
    "dddd Mo D, YYYY",
    "dddd MM D, YY",
    "dddd MM D, YYYY",
    "dddd MMM D, YY",
    "dddd MMM D, YYYY",
    "dddd MMMM D, YY",
    "dddd MMMM D, YYYY",
    "dddd M DD, YY",
    "dddd M DD, YYYY",
    "dddd Mo DD, YY",
    "dddd Mo DD, YYYY",
    "dddd MM DD, YY",
    "dddd MM DD, YYYY",
    "dddd MMM DD, YY",
    "dddd MMM DD, YYYY",
    "dddd MMMM DD, YY",
    "dddd MMMM DD, YYYY",
    "ddd, D-M",
    "ddd, D-Mo",
    "ddd, D-MM",
    "ddd, D-MMM",
    "ddd, D-MMMM",
    "ddd, Do-M",
    "ddd, Do-Mo",
    "ddd, Do-MM",
    "ddd, Do-MMM",
    "ddd, Do-MMMM",
    "ddd, DD-M",
    "ddd, DD-Mo",
    "ddd, DD-MM",
    "ddd, DD-MMM",
    "ddd, DD-MMMM",
    "ddd, M-YY",
    "ddd, M-YYYY",
    "ddd, Mo-YY",
    "ddd, Mo-YYYY",
    "ddd, MM-YY",
    "ddd, MM-YYYY",
    "ddd, MMM-YY",
    "ddd, MMM-YYYY",
    "ddd, MMMM-YY",
    "ddd, MMMM-YYYY",
    "ddd, D-M-YY",
    "ddd, D-M-YYYY",
    "ddd, D-Mo-YY",
    "ddd, D-Mo-YYYY",
    "ddd, D-MM-YY",
    "ddd, D-MM-YYYY",
    "ddd, D-MMM-YY",
    "ddd, D-MMM-YYYY",
    "ddd, D-MMMM-YY",
    "ddd, D-MMMM-YYYY",
    "ddd, Do-M-YY",
    "ddd, Do-M-YYYY",
    "ddd, Do-Mo-YY",
    "ddd, Do-Mo-YYYY",
    "ddd, Do-MM-YY",
    "ddd, Do-MM-YYYY",
    "ddd, Do-MMM-YY",
    "ddd, Do-MMM-YYYY",
    "ddd, Do-MMMM-YY",
    "ddd, Do-MMMM-YYYY",
    "ddd, DD-M-YY",
    "ddd, DD-M-YYYY",
    "ddd, DD-Mo-YY",
    "ddd, DD-Mo-YYYY",
    "ddd, DD-MM-YY",
    "ddd, DD-MM-YYYY",
    "ddd, DD-MMM-YY",
    "ddd, DD-MMM-YYYY",
    "ddd, DD-MMMM-YY",
    "ddd, DD-MMMM-YYYY",
    "ddd, M-D-YY",
    "ddd, M-D-YYYY",
    "ddd, M-Do-YY",
    "ddd, M-Do-YYYY",
    "ddd, M-DD-YY",
    "ddd, M-DD-YYYY",
    "ddd, Mo-D-YY",
    "ddd, Mo-D-YYYY",
    "ddd, Mo-Do-YY",
    "ddd, Mo-Do-YYYY",
    "ddd, Mo-DD-YY",
    "ddd, Mo-DD-YYYY",
    "ddd, MM-D-YY",
    "ddd, MM-D-YYYY",
    "ddd, MM-Do-YY",
    "ddd, MM-Do-YYYY",
    "ddd, MM-DD-YY",
    "ddd, MM-DD-YYYY",
    "ddd, MMM-D-YY",
    "ddd, MMM-D-YYYY",
    "ddd, MMM-Do-YY",
    "ddd, MMM-Do-YYYY",
    "ddd, MMM-DD-YY",
    "ddd, MMM-DD-YYYY",
    "ddd, MMMM-D-YY",
    "ddd, MMMM-D-YYYY",
    "ddd, MMMM-Do-YY",
    "ddd, MMMM-Do-YYYY",
    "ddd, MMMM-DD-YY",
    "ddd, MMMM-DD-YYYY",
    "ddd, M-D",
    "ddd, M-Do",
    "ddd, M-DD",
    "ddd, Mo-D",
    "ddd, Mo-Do",
    "ddd, Mo-DD",
    "ddd, MM-D",
    "ddd, MM-Do",
    "ddd, MM-DD",
    "ddd, MMM-D",
    "ddd, MMM-Do",
    "ddd, MMM-DD",
    "ddd, MMMM-D",
    "ddd, MMMM-Do",
    "ddd, MMMM-DD",
    "ddd, YY-M",
    "ddd, YY-Mo",
    "ddd, YY-MM",
    "ddd, YY-MMM",
    "ddd, YY-MMMM",
    "ddd, YYYY-M",
    "ddd, YYYY-Mo",
    "ddd, YYYY-MM",
    "ddd, YYYY-MMM",
    "ddd, YYYY-MMMM",
    "ddd, YY-M-D",
    "ddd, YY-M-Do",
    "ddd, YY-M-DD",
    "ddd, YY-Mo-D",
    "ddd, YY-Mo-Do",
    "ddd, YY-Mo-DD",
    "ddd, YY-MM-D",
    "ddd, YY-MM-Do",
    "ddd, YY-MM-DD",
    "ddd, YY-MMM-D",
    "ddd, YY-MMM-Do",
    "ddd, YY-MMM-DD",
    "ddd, YY-MMMM-D",
    "ddd, YY-MMMM-Do",
    "ddd, YY-MMMM-DD",
    "ddd, YYYY-M-D",
    "ddd, YYYY-M-Do",
    "ddd, YYYY-M-DD",
    "ddd, YYYY-Mo-D",
    "ddd, YYYY-Mo-Do",
    "ddd, YYYY-Mo-DD",
    "ddd, YYYY-MM-D",
    "ddd, YYYY-MM-Do",
    "ddd, YYYY-MM-DD",
    "ddd, YYYY-MMM-D",
    "ddd, YYYY-MMM-Do",
    "ddd, YYYY-MMM-DD",
    "ddd, YYYY-MMMM-D",
    "ddd, YYYY-MMMM-Do",
    "ddd, YYYY-MMMM-DD",
    "ddd, YY-D-M",
    "ddd, YY-D-Mo",
    "ddd, YY-D-MM",
    "ddd, YY-D-MMM",
    "ddd, YY-D-MMMM",
    "ddd, YY-Do-M",
    "ddd, YY-Do-Mo",
    "ddd, YY-Do-MM",
    "ddd, YY-Do-MMM",
    "ddd, YY-Do-MMMM",
    "ddd, YY-DD-M",
    "ddd, YY-DD-Mo",
    "ddd, YY-DD-MM",
    "ddd, YY-DD-MMM",
    "ddd, YY-DD-MMMM",
    "ddd, YYYY-D-M",
    "ddd, YYYY-D-Mo",
    "ddd, YYYY-D-MM",
    "ddd, YYYY-D-MMM",
    "ddd, YYYY-D-MMMM",
    "ddd, YYYY-Do-M",
    "ddd, YYYY-Do-Mo",
    "ddd, YYYY-Do-MM",
    "ddd, YYYY-Do-MMM",
    "ddd, YYYY-Do-MMMM",
    "ddd, YYYY-DD-M",
    "ddd, YYYY-DD-Mo",
    "ddd, YYYY-DD-MM",
    "ddd, YYYY-DD-MMM",
    "ddd, YYYY-DD-MMMM",
    "ddd, D/M",
    "ddd, D/Mo",
    "ddd, D/MM",
    "ddd, D/MMM",
    "ddd, D/MMMM",
    "ddd, Do/M",
    "ddd, Do/Mo",
    "ddd, Do/MM",
    "ddd, Do/MMM",
    "ddd, Do/MMMM",
    "ddd, DD/M",
    "ddd, DD/Mo",
    "ddd, DD/MM",
    "ddd, DD/MMM",
    "ddd, DD/MMMM",
    "ddd, M/YY",
    "ddd, M/YYYY",
    "ddd, Mo/YY",
    "ddd, Mo/YYYY",
    "ddd, MM/YY",
    "ddd, MM/YYYY",
    "ddd, MMM/YY",
    "ddd, MMM/YYYY",
    "ddd, MMMM/YY",
    "ddd, MMMM/YYYY",
    "ddd, D/M/YY",
    "ddd, D/M/YYYY",
    "ddd, D/Mo/YY",
    "ddd, D/Mo/YYYY",
    "ddd, D/MM/YY",
    "ddd, D/MM/YYYY",
    "ddd, D/MMM/YY",
    "ddd, D/MMM/YYYY",
    "ddd, D/MMMM/YY",
    "ddd, D/MMMM/YYYY",
    "ddd, Do/M/YY",
    "ddd, Do/M/YYYY",
    "ddd, Do/Mo/YY",
    "ddd, Do/Mo/YYYY",
    "ddd, Do/MM/YY",
    "ddd, Do/MM/YYYY",
    "ddd, Do/MMM/YY",
    "ddd, Do/MMM/YYYY",
    "ddd, Do/MMMM/YY",
    "ddd, Do/MMMM/YYYY",
    "ddd, DD/M/YY",
    "ddd, DD/M/YYYY",
    "ddd, DD/Mo/YY",
    "ddd, DD/Mo/YYYY",
    "ddd, DD/MM/YY",
    "ddd, DD/MM/YYYY",
    "ddd, DD/MMM/YY",
    "ddd, DD/MMM/YYYY",
    "ddd, DD/MMMM/YY",
    "ddd, DD/MMMM/YYYY",
    "ddd, M/D/YY",
    "ddd, M/D/YYYY",
    "ddd, M/Do/YY",
    "ddd, M/Do/YYYY",
    "ddd, M/DD/YY",
    "ddd, M/DD/YYYY",
    "ddd, Mo/D/YY",
    "ddd, Mo/D/YYYY",
    "ddd, Mo/Do/YY",
    "ddd, Mo/Do/YYYY",
    "ddd, Mo/DD/YY",
    "ddd, Mo/DD/YYYY",
    "ddd, MM/D/YY",
    "ddd, MM/D/YYYY",
    "ddd, MM/Do/YY",
    "ddd, MM/Do/YYYY",
    "ddd, MM/DD/YY",
    "ddd, MM/DD/YYYY",
    "ddd, MMM/D/YY",
    "ddd, MMM/D/YYYY",
    "ddd, MMM/Do/YY",
    "ddd, MMM/Do/YYYY",
    "ddd, MMM/DD/YY",
    "ddd, MMM/DD/YYYY",
    "ddd, MMMM/D/YY",
    "ddd, MMMM/D/YYYY",
    "ddd, MMMM/Do/YY",
    "ddd, MMMM/Do/YYYY",
    "ddd, MMMM/DD/YY",
    "ddd, MMMM/DD/YYYY",
    "ddd, M/D",
    "ddd, M/Do",
    "ddd, M/DD",
    "ddd, Mo/D",
    "ddd, Mo/Do",
    "ddd, Mo/DD",
    "ddd, MM/D",
    "ddd, MM/Do",
    "ddd, MM/DD",
    "ddd, MMM/D",
    "ddd, MMM/Do",
    "ddd, MMM/DD",
    "ddd, MMMM/D",
    "ddd, MMMM/Do",
    "ddd, MMMM/DD",
    "ddd, YY/M",
    "ddd, YY/Mo",
    "ddd, YY/MM",
    "ddd, YY/MMM",
    "ddd, YY/MMMM",
    "ddd, YYYY/M",
    "ddd, YYYY/Mo",
    "ddd, YYYY/MM",
    "ddd, YYYY/MMM",
    "ddd, YYYY/MMMM",
    "ddd, YY/M/D",
    "ddd, YY/M/Do",
    "ddd, YY/M/DD",
    "ddd, YY/Mo/D",
    "ddd, YY/Mo/Do",
    "ddd, YY/Mo/DD",
    "ddd, YY/MM/D",
    "ddd, YY/MM/Do",
    "ddd, YY/MM/DD",
    "ddd, YY/MMM/D",
    "ddd, YY/MMM/Do",
    "ddd, YY/MMM/DD",
    "ddd, YY/MMMM/D",
    "ddd, YY/MMMM/Do",
    "ddd, YY/MMMM/DD",
    "ddd, YYYY/M/D",
    "ddd, YYYY/M/Do",
    "ddd, YYYY/M/DD",
    "ddd, YYYY/Mo/D",
    "ddd, YYYY/Mo/Do",
    "ddd, YYYY/Mo/DD",
    "ddd, YYYY/MM/D",
    "ddd, YYYY/MM/Do",
    "ddd, YYYY/MM/DD",
    "ddd, YYYY/MMM/D",
    "ddd, YYYY/MMM/Do",
    "ddd, YYYY/MMM/DD",
    "ddd, YYYY/MMMM/D",
    "ddd, YYYY/MMMM/Do",
    "ddd, YYYY/MMMM/DD",
    "ddd, YY/D/M",
    "ddd, YY/D/Mo",
    "ddd, YY/D/MM",
    "ddd, YY/D/MMM",
    "ddd, YY/D/MMMM",
    "ddd, YY/Do/M",
    "ddd, YY/Do/Mo",
    "ddd, YY/Do/MM",
    "ddd, YY/Do/MMM",
    "ddd, YY/Do/MMMM",
    "ddd, YY/DD/M",
    "ddd, YY/DD/Mo",
    "ddd, YY/DD/MM",
    "ddd, YY/DD/MMM",
    "ddd, YY/DD/MMMM",
    "ddd, YYYY/D/M",
    "ddd, YYYY/D/Mo",
    "ddd, YYYY/D/MM",
    "ddd, YYYY/D/MMM",
    "ddd, YYYY/D/MMMM",
    "ddd, YYYY/Do/M",
    "ddd, YYYY/Do/Mo",
    "ddd, YYYY/Do/MM",
    "ddd, YYYY/Do/MMM",
    "ddd, YYYY/Do/MMMM",
    "ddd, YYYY/DD/M",
    "ddd, YYYY/DD/Mo",
    "ddd, YYYY/DD/MM",
    "ddd, YYYY/DD/MMM",
    "ddd, YYYY/DD/MMMM",
    "ddd, D.M",
    "ddd, D.Mo",
    "ddd, D.MM",
    "ddd, D.MMM",
    "ddd, D.MMMM",
    "ddd, Do.M",
    "ddd, Do.Mo",
    "ddd, Do.MM",
    "ddd, Do.MMM",
    "ddd, Do.MMMM",
    "ddd, DD.M",
    "ddd, DD.Mo",
    "ddd, DD.MM",
    "ddd, DD.MMM",
    "ddd, DD.MMMM",
    "ddd, M.YY",
    "ddd, M.YYYY",
    "ddd, Mo.YY",
    "ddd, Mo.YYYY",
    "ddd, MM.YY",
    "ddd, MM.YYYY",
    "ddd, MMM.YY",
    "ddd, MMM.YYYY",
    "ddd, MMMM.YY",
    "ddd, MMMM.YYYY",
    "ddd, D.M.YY",
    "ddd, D.M.YYYY",
    "ddd, D.Mo.YY",
    "ddd, D.Mo.YYYY",
    "ddd, D.MM.YY",
    "ddd, D.MM.YYYY",
    "ddd, D.MMM.YY",
    "ddd, D.MMM.YYYY",
    "ddd, D.MMMM.YY",
    "ddd, D.MMMM.YYYY",
    "ddd, Do.M.YY",
    "ddd, Do.M.YYYY",
    "ddd, Do.Mo.YY",
    "ddd, Do.Mo.YYYY",
    "ddd, Do.MM.YY",
    "ddd, Do.MM.YYYY",
    "ddd, Do.MMM.YY",
    "ddd, Do.MMM.YYYY",
    "ddd, Do.MMMM.YY",
    "ddd, Do.MMMM.YYYY",
    "ddd, DD.M.YY",
    "ddd, DD.M.YYYY",
    "ddd, DD.Mo.YY",
    "ddd, DD.Mo.YYYY",
    "ddd, DD.MM.YY",
    "ddd, DD.MM.YYYY",
    "ddd, DD.MMM.YY",
    "ddd, DD.MMM.YYYY",
    "ddd, DD.MMMM.YY",
    "ddd, DD.MMMM.YYYY",
    "ddd, M.D.YY",
    "ddd, M.D.YYYY",
    "ddd, M.Do.YY",
    "ddd, M.Do.YYYY",
    "ddd, M.DD.YY",
    "ddd, M.DD.YYYY",
    "ddd, Mo.D.YY",
    "ddd, Mo.D.YYYY",
    "ddd, Mo.Do.YY",
    "ddd, Mo.Do.YYYY",
    "ddd, Mo.DD.YY",
    "ddd, Mo.DD.YYYY",
    "ddd, MM.D.YY",
    "ddd, MM.D.YYYY",
    "ddd, MM.Do.YY",
    "ddd, MM.Do.YYYY",
    "ddd, MM.DD.YY",
    "ddd, MM.DD.YYYY",
    "ddd, MMM.D.YY",
    "ddd, MMM.D.YYYY",
    "ddd, MMM.Do.YY",
    "ddd, MMM.Do.YYYY",
    "ddd, MMM.DD.YY",
    "ddd, MMM.DD.YYYY",
    "ddd, MMMM.D.YY",
    "ddd, MMMM.D.YYYY",
    "ddd, MMMM.Do.YY",
    "ddd, MMMM.Do.YYYY",
    "ddd, MMMM.DD.YY",
    "ddd, MMMM.DD.YYYY",
    "ddd, M.D",
    "ddd, M.Do",
    "ddd, M.DD",
    "ddd, Mo.D",
    "ddd, Mo.Do",
    "ddd, Mo.DD",
    "ddd, MM.D",
    "ddd, MM.Do",
    "ddd, MM.DD",
    "ddd, MMM.D",
    "ddd, MMM.Do",
    "ddd, MMM.DD",
    "ddd, MMMM.D",
    "ddd, MMMM.Do",
    "ddd, MMMM.DD",
    "ddd, YY.M",
    "ddd, YY.Mo",
    "ddd, YY.MM",
    "ddd, YY.MMM",
    "ddd, YY.MMMM",
    "ddd, YYYY.M",
    "ddd, YYYY.Mo",
    "ddd, YYYY.MM",
    "ddd, YYYY.MMM",
    "ddd, YYYY.MMMM",
    "ddd, YY.M.D",
    "ddd, YY.M.Do",
    "ddd, YY.M.DD",
    "ddd, YY.Mo.D",
    "ddd, YY.Mo.Do",
    "ddd, YY.Mo.DD",
    "ddd, YY.MM.D",
    "ddd, YY.MM.Do",
    "ddd, YY.MM.DD",
    "ddd, YY.MMM.D",
    "ddd, YY.MMM.Do",
    "ddd, YY.MMM.DD",
    "ddd, YY.MMMM.D",
    "ddd, YY.MMMM.Do",
    "ddd, YY.MMMM.DD",
    "ddd, YYYY.M.D",
    "ddd, YYYY.M.Do",
    "ddd, YYYY.M.DD",
    "ddd, YYYY.Mo.D",
    "ddd, YYYY.Mo.Do",
    "ddd, YYYY.Mo.DD",
    "ddd, YYYY.MM.D",
    "ddd, YYYY.MM.Do",
    "ddd, YYYY.MM.DD",
    "ddd, YYYY.MMM.D",
    "ddd, YYYY.MMM.Do",
    "ddd, YYYY.MMM.DD",
    "ddd, YYYY.MMMM.D",
    "ddd, YYYY.MMMM.Do",
    "ddd, YYYY.MMMM.DD",
    "ddd, YY.D.M",
    "ddd, YY.D.Mo",
    "ddd, YY.D.MM",
    "ddd, YY.D.MMM",
    "ddd, YY.D.MMMM",
    "ddd, YY.Do.M",
    "ddd, YY.Do.Mo",
    "ddd, YY.Do.MM",
    "ddd, YY.Do.MMM",
    "ddd, YY.Do.MMMM",
    "ddd, YY.DD.M",
    "ddd, YY.DD.Mo",
    "ddd, YY.DD.MM",
    "ddd, YY.DD.MMM",
    "ddd, YY.DD.MMMM",
    "ddd, YYYY.D.M",
    "ddd, YYYY.D.Mo",
    "ddd, YYYY.D.MM",
    "ddd, YYYY.D.MMM",
    "ddd, YYYY.D.MMMM",
    "ddd, YYYY.Do.M",
    "ddd, YYYY.Do.Mo",
    "ddd, YYYY.Do.MM",
    "ddd, YYYY.Do.MMM",
    "ddd, YYYY.Do.MMMM",
    "ddd, YYYY.DD.M",
    "ddd, YYYY.DD.Mo",
    "ddd, YYYY.DD.MM",
    "ddd, YYYY.DD.MMM",
    "ddd, YYYY.DD.MMMM",
    "ddd, D M",
    "ddd, D Mo",
    "ddd, D MM",
    "ddd, D MMM",
    "ddd, D MMMM",
    "ddd, Do M",
    "ddd, Do Mo",
    "ddd, Do MM",
    "ddd, Do MMM",
    "ddd, Do MMMM",
    "ddd, DD M",
    "ddd, DD Mo",
    "ddd, DD MM",
    "ddd, DD MMM",
    "ddd, DD MMMM",
    "ddd, M YY",
    "ddd, M YYYY",
    "ddd, Mo YY",
    "ddd, Mo YYYY",
    "ddd, MM YY",
    "ddd, MM YYYY",
    "ddd, MMM YY",
    "ddd, MMM YYYY",
    "ddd, MMMM YY",
    "ddd, MMMM YYYY",
    "ddd, D M YY",
    "ddd, D M YYYY",
    "ddd, D Mo YY",
    "ddd, D Mo YYYY",
    "ddd, D MM YY",
    "ddd, D MM YYYY",
    "ddd, D MMM YY",
    "ddd, D MMM YYYY",
    "ddd, D MMMM YY",
    "ddd, D MMMM YYYY",
    "ddd, Do M YY",
    "ddd, Do M YYYY",
    "ddd, Do Mo YY",
    "ddd, Do Mo YYYY",
    "ddd, Do MM YY",
    "ddd, Do MM YYYY",
    "ddd, Do MMM YY",
    "ddd, Do MMM YYYY",
    "ddd, Do MMMM YY",
    "ddd, Do MMMM YYYY",
    "ddd, DD M YY",
    "ddd, DD M YYYY",
    "ddd, DD Mo YY",
    "ddd, DD Mo YYYY",
    "ddd, DD MM YY",
    "ddd, DD MM YYYY",
    "ddd, DD MMM YY",
    "ddd, DD MMM YYYY",
    "ddd, DD MMMM YY",
    "ddd, DD MMMM YYYY",
    "ddd, M D YY",
    "ddd, M D YYYY",
    "ddd, M Do YY",
    "ddd, M Do YYYY",
    "ddd, M DD YY",
    "ddd, M DD YYYY",
    "ddd, Mo D YY",
    "ddd, Mo D YYYY",
    "ddd, Mo Do YY",
    "ddd, Mo Do YYYY",
    "ddd, Mo DD YY",
    "ddd, Mo DD YYYY",
    "ddd, MM D YY",
    "ddd, MM D YYYY",
    "ddd, MM Do YY",
    "ddd, MM Do YYYY",
    "ddd, MM DD YY",
    "ddd, MM DD YYYY",
    "ddd, MMM D YY",
    "ddd, MMM D YYYY",
    "ddd, MMM Do YY",
    "ddd, MMM Do YYYY",
    "ddd, MMM DD YY",
    "ddd, MMM DD YYYY",
    "ddd, MMMM D YY",
    "ddd, MMMM D YYYY",
    "ddd, MMMM Do YY",
    "ddd, MMMM Do YYYY",
    "ddd, MMMM DD YY",
    "ddd, MMMM DD YYYY",
    "ddd, M D",
    "ddd, M Do",
    "ddd, M DD",
    "ddd, Mo D",
    "ddd, Mo Do",
    "ddd, Mo DD",
    "ddd, MM D",
    "ddd, MM Do",
    "ddd, MM DD",
    "ddd, MMM D",
    "ddd, MMM Do",
    "ddd, MMM DD",
    "ddd, MMMM D",
    "ddd, MMMM Do",
    "ddd, MMMM DD",
    "ddd, YY M",
    "ddd, YY Mo",
    "ddd, YY MM",
    "ddd, YY MMM",
    "ddd, YY MMMM",
    "ddd, YYYY M",
    "ddd, YYYY Mo",
    "ddd, YYYY MM",
    "ddd, YYYY MMM",
    "ddd, YYYY MMMM",
    "ddd, YY M D",
    "ddd, YY M Do",
    "ddd, YY M DD",
    "ddd, YY Mo D",
    "ddd, YY Mo Do",
    "ddd, YY Mo DD",
    "ddd, YY MM D",
    "ddd, YY MM Do",
    "ddd, YY MM DD",
    "ddd, YY MMM D",
    "ddd, YY MMM Do",
    "ddd, YY MMM DD",
    "ddd, YY MMMM D",
    "ddd, YY MMMM Do",
    "ddd, YY MMMM DD",
    "ddd, YYYY M D",
    "ddd, YYYY M Do",
    "ddd, YYYY M DD",
    "ddd, YYYY Mo D",
    "ddd, YYYY Mo Do",
    "ddd, YYYY Mo DD",
    "ddd, YYYY MM D",
    "ddd, YYYY MM Do",
    "ddd, YYYY MM DD",
    "ddd, YYYY MMM D",
    "ddd, YYYY MMM Do",
    "ddd, YYYY MMM DD",
    "ddd, YYYY MMMM D",
    "ddd, YYYY MMMM Do",
    "ddd, YYYY MMMM DD",
    "ddd, YY D M",
    "ddd, YY D Mo",
    "ddd, YY D MM",
    "ddd, YY D MMM",
    "ddd, YY D MMMM",
    "ddd, YY Do M",
    "ddd, YY Do Mo",
    "ddd, YY Do MM",
    "ddd, YY Do MMM",
    "ddd, YY Do MMMM",
    "ddd, YY DD M",
    "ddd, YY DD Mo",
    "ddd, YY DD MM",
    "ddd, YY DD MMM",
    "ddd, YY DD MMMM",
    "ddd, YYYY D M",
    "ddd, YYYY D Mo",
    "ddd, YYYY D MM",
    "ddd, YYYY D MMM",
    "ddd, YYYY D MMMM",
    "ddd, YYYY Do M",
    "ddd, YYYY Do Mo",
    "ddd, YYYY Do MM",
    "ddd, YYYY Do MMM",
    "ddd, YYYY Do MMMM",
    "ddd, YYYY DD M",
    "ddd, YYYY DD Mo",
    "ddd, YYYY DD MM",
    "ddd, YYYY DD MMM",
    "ddd, YYYY DD MMMM",
    "ddd, DM",
    "ddd, DMo",
    "ddd, DMM",
    "ddd, DMMM",
    "ddd, DMMMM",
    "ddd, DoM",
    "ddd, DoMo",
    "ddd, DoMM",
    "ddd, DoMMM",
    "ddd, DoMMMM",
    "ddd, DDM",
    "ddd, DDMo",
    "ddd, DDMM",
    "ddd, DDMMM",
    "ddd, DDMMMM",
    "ddd, MYY",
    "ddd, MYYYY",
    "ddd, MoYY",
    "ddd, MoYYYY",
    "ddd, MMYY",
    "ddd, MMYYYY",
    "ddd, MMMYY",
    "ddd, MMMYYYY",
    "ddd, MMMMYY",
    "ddd, MMMMYYYY",
    "ddd, DMYY",
    "ddd, DMYYYY",
    "ddd, DMoYY",
    "ddd, DMoYYYY",
    "ddd, DMMYY",
    "ddd, DMMYYYY",
    "ddd, DMMMYY",
    "ddd, DMMMYYYY",
    "ddd, DMMMMYY",
    "ddd, DMMMMYYYY",
    "ddd, DoMYY",
    "ddd, DoMYYYY",
    "ddd, DoMoYY",
    "ddd, DoMoYYYY",
    "ddd, DoMMYY",
    "ddd, DoMMYYYY",
    "ddd, DoMMMYY",
    "ddd, DoMMMYYYY",
    "ddd, DoMMMMYY",
    "ddd, DoMMMMYYYY",
    "ddd, DDMYY",
    "ddd, DDMYYYY",
    "ddd, DDMoYY",
    "ddd, DDMoYYYY",
    "ddd, DDMMYY",
    "ddd, DDMMYYYY",
    "ddd, DDMMMYY",
    "ddd, DDMMMYYYY",
    "ddd, DDMMMMYY",
    "ddd, DDMMMMYYYY",
    "ddd, MDYY",
    "ddd, MDYYYY",
    "ddd, MDoYY",
    "ddd, MDoYYYY",
    "ddd, MDDYY",
    "ddd, MDDYYYY",
    "ddd, MoDYY",
    "ddd, MoDYYYY",
    "ddd, MoDoYY",
    "ddd, MoDoYYYY",
    "ddd, MoDDYY",
    "ddd, MoDDYYYY",
    "ddd, MMDYY",
    "ddd, MMDYYYY",
    "ddd, MMDoYY",
    "ddd, MMDoYYYY",
    "ddd, MMDDYY",
    "ddd, MMDDYYYY",
    "ddd, MMMDYY",
    "ddd, MMMDYYYY",
    "ddd, MMMDoYY",
    "ddd, MMMDoYYYY",
    "ddd, MMMDDYY",
    "ddd, MMMDDYYYY",
    "ddd, MMMMDYY",
    "ddd, MMMMDYYYY",
    "ddd, MMMMDoYY",
    "ddd, MMMMDoYYYY",
    "ddd, MMMMDDYY",
    "ddd, MMMMDDYYYY",
    "ddd, MD",
    "ddd, MDo",
    "ddd, MDD",
    "ddd, MoD",
    "ddd, MoDo",
    "ddd, MoDD",
    "ddd, MMD",
    "ddd, MMDo",
    "ddd, MMDD",
    "ddd, MMMD",
    "ddd, MMMDo",
    "ddd, MMMDD",
    "ddd, MMMMD",
    "ddd, MMMMDo",
    "ddd, MMMMDD",
    "ddd, YYM",
    "ddd, YYMo",
    "ddd, YYMM",
    "ddd, YYMMM",
    "ddd, YYMMMM",
    "ddd, YYYYM",
    "ddd, YYYYMo",
    "ddd, YYYYMM",
    "ddd, YYYYMMM",
    "ddd, YYYYMMMM",
    "ddd, YYMD",
    "ddd, YYMDo",
    "ddd, YYMDD",
    "ddd, YYMoD",
    "ddd, YYMoDo",
    "ddd, YYMoDD",
    "ddd, YYMMD",
    "ddd, YYMMDo",
    "ddd, YYMMDD",
    "ddd, YYMMMD",
    "ddd, YYMMMDo",
    "ddd, YYMMMDD",
    "ddd, YYMMMMD",
    "ddd, YYMMMMDo",
    "ddd, YYMMMMDD",
    "ddd, YYYYMD",
    "ddd, YYYYMDo",
    "ddd, YYYYMDD",
    "ddd, YYYYMoD",
    "ddd, YYYYMoDo",
    "ddd, YYYYMoDD",
    "ddd, YYYYMMD",
    "ddd, YYYYMMDo",
    "ddd, YYYYMMDD",
    "ddd, YYYYMMMD",
    "ddd, YYYYMMMDo",
    "ddd, YYYYMMMDD",
    "ddd, YYYYMMMMD",
    "ddd, YYYYMMMMDo",
    "ddd, YYYYMMMMDD",
    "ddd, YYDM",
    "ddd, YYDMo",
    "ddd, YYDMM",
    "ddd, YYDMMM",
    "ddd, YYDMMMM",
    "ddd, YYDoM",
    "ddd, YYDoMo",
    "ddd, YYDoMM",
    "ddd, YYDoMMM",
    "ddd, YYDoMMMM",
    "ddd, YYDDM",
    "ddd, YYDDMo",
    "ddd, YYDDMM",
    "ddd, YYDDMMM",
    "ddd, YYDDMMMM",
    "ddd, YYYYDM",
    "ddd, YYYYDMo",
    "ddd, YYYYDMM",
    "ddd, YYYYDMMM",
    "ddd, YYYYDMMMM",
    "ddd, YYYYDoM",
    "ddd, YYYYDoMo",
    "ddd, YYYYDoMM",
    "ddd, YYYYDoMMM",
    "ddd, YYYYDoMMMM",
    "ddd, YYYYDDM",
    "ddd, YYYYDDMo",
    "ddd, YYYYDDMM",
    "ddd, YYYYDDMMM",
    "ddd, YYYYDDMMMM",
    "ddd, M Do, YY",
    "ddd, M Do, YYYY",
    "ddd, Mo Do, YY",
    "ddd, Mo Do, YYYY",
    "ddd, MM Do, YY",
    "ddd, MM Do, YYYY",
    "ddd, MMM Do, YY",
    "ddd, MMM Do, YYYY",
    "ddd, MMMM Do, YY",
    "ddd, MMMM Do, YYYY",
    "ddd, M D, YY",
    "ddd, M D, YYYY",
    "ddd, Mo D, YY",
    "ddd, Mo D, YYYY",
    "ddd, MM D, YY",
    "ddd, MM D, YYYY",
    "ddd, MMM D, YY",
    "ddd, MMM D, YYYY",
    "ddd, MMMM D, YY",
    "ddd, MMMM D, YYYY",
    "ddd, M DD, YY",
    "ddd, M DD, YYYY",
    "ddd, Mo DD, YY",
    "ddd, Mo DD, YYYY",
    "ddd, MM DD, YY",
    "ddd, MM DD, YYYY",
    "ddd, MMM DD, YY",
    "ddd, MMM DD, YYYY",
    "ddd, MMMM DD, YY",
    "ddd, MMMM DD, YYYY",
    "dddd, D-M",
    "dddd, D-Mo",
    "dddd, D-MM",
    "dddd, D-MMM",
    "dddd, D-MMMM",
    "dddd, Do-M",
    "dddd, Do-Mo",
    "dddd, Do-MM",
    "dddd, Do-MMM",
    "dddd, Do-MMMM",
    "dddd, DD-M",
    "dddd, DD-Mo",
    "dddd, DD-MM",
    "dddd, DD-MMM",
    "dddd, DD-MMMM",
    "dddd, M-YY",
    "dddd, M-YYYY",
    "dddd, Mo-YY",
    "dddd, Mo-YYYY",
    "dddd, MM-YY",
    "dddd, MM-YYYY",
    "dddd, MMM-YY",
    "dddd, MMM-YYYY",
    "dddd, MMMM-YY",
    "dddd, MMMM-YYYY",
    "dddd, D-M-YY",
    "dddd, D-M-YYYY",
    "dddd, D-Mo-YY",
    "dddd, D-Mo-YYYY",
    "dddd, D-MM-YY",
    "dddd, D-MM-YYYY",
    "dddd, D-MMM-YY",
    "dddd, D-MMM-YYYY",
    "dddd, D-MMMM-YY",
    "dddd, D-MMMM-YYYY",
    "dddd, Do-M-YY",
    "dddd, Do-M-YYYY",
    "dddd, Do-Mo-YY",
    "dddd, Do-Mo-YYYY",
    "dddd, Do-MM-YY",
    "dddd, Do-MM-YYYY",
    "dddd, Do-MMM-YY",
    "dddd, Do-MMM-YYYY",
    "dddd, Do-MMMM-YY",
    "dddd, Do-MMMM-YYYY",
    "dddd, DD-M-YY",
    "dddd, DD-M-YYYY",
    "dddd, DD-Mo-YY",
    "dddd, DD-Mo-YYYY",
    "dddd, DD-MM-YY",
    "dddd, DD-MM-YYYY",
    "dddd, DD-MMM-YY",
    "dddd, DD-MMM-YYYY",
    "dddd, DD-MMMM-YY",
    "dddd, DD-MMMM-YYYY",
    "dddd, M-D-YY",
    "dddd, M-D-YYYY",
    "dddd, M-Do-YY",
    "dddd, M-Do-YYYY",
    "dddd, M-DD-YY",
    "dddd, M-DD-YYYY",
    "dddd, Mo-D-YY",
    "dddd, Mo-D-YYYY",
    "dddd, Mo-Do-YY",
    "dddd, Mo-Do-YYYY",
    "dddd, Mo-DD-YY",
    "dddd, Mo-DD-YYYY",
    "dddd, MM-D-YY",
    "dddd, MM-D-YYYY",
    "dddd, MM-Do-YY",
    "dddd, MM-Do-YYYY",
    "dddd, MM-DD-YY",
    "dddd, MM-DD-YYYY",
    "dddd, MMM-D-YY",
    "dddd, MMM-D-YYYY",
    "dddd, MMM-Do-YY",
    "dddd, MMM-Do-YYYY",
    "dddd, MMM-DD-YY",
    "dddd, MMM-DD-YYYY",
    "dddd, MMMM-D-YY",
    "dddd, MMMM-D-YYYY",
    "dddd, MMMM-Do-YY",
    "dddd, MMMM-Do-YYYY",
    "dddd, MMMM-DD-YY",
    "dddd, MMMM-DD-YYYY",
    "dddd, M-D",
    "dddd, M-Do",
    "dddd, M-DD",
    "dddd, Mo-D",
    "dddd, Mo-Do",
    "dddd, Mo-DD",
    "dddd, MM-D",
    "dddd, MM-Do",
    "dddd, MM-DD",
    "dddd, MMM-D",
    "dddd, MMM-Do",
    "dddd, MMM-DD",
    "dddd, MMMM-D",
    "dddd, MMMM-Do",
    "dddd, MMMM-DD",
    "dddd, YY-M",
    "dddd, YY-Mo",
    "dddd, YY-MM",
    "dddd, YY-MMM",
    "dddd, YY-MMMM",
    "dddd, YYYY-M",
    "dddd, YYYY-Mo",
    "dddd, YYYY-MM",
    "dddd, YYYY-MMM",
    "dddd, YYYY-MMMM",
    "dddd, YY-M-D",
    "dddd, YY-M-Do",
    "dddd, YY-M-DD",
    "dddd, YY-Mo-D",
    "dddd, YY-Mo-Do",
    "dddd, YY-Mo-DD",
    "dddd, YY-MM-D",
    "dddd, YY-MM-Do",
    "dddd, YY-MM-DD",
    "dddd, YY-MMM-D",
    "dddd, YY-MMM-Do",
    "dddd, YY-MMM-DD",
    "dddd, YY-MMMM-D",
    "dddd, YY-MMMM-Do",
    "dddd, YY-MMMM-DD",
    "dddd, YYYY-M-D",
    "dddd, YYYY-M-Do",
    "dddd, YYYY-M-DD",
    "dddd, YYYY-Mo-D",
    "dddd, YYYY-Mo-Do",
    "dddd, YYYY-Mo-DD",
    "dddd, YYYY-MM-D",
    "dddd, YYYY-MM-Do",
    "dddd, YYYY-MM-DD",
    "dddd, YYYY-MMM-D",
    "dddd, YYYY-MMM-Do",
    "dddd, YYYY-MMM-DD",
    "dddd, YYYY-MMMM-D",
    "dddd, YYYY-MMMM-Do",
    "dddd, YYYY-MMMM-DD",
    "dddd, YY-D-M",
    "dddd, YY-D-Mo",
    "dddd, YY-D-MM",
    "dddd, YY-D-MMM",
    "dddd, YY-D-MMMM",
    "dddd, YY-Do-M",
    "dddd, YY-Do-Mo",
    "dddd, YY-Do-MM",
    "dddd, YY-Do-MMM",
    "dddd, YY-Do-MMMM",
    "dddd, YY-DD-M",
    "dddd, YY-DD-Mo",
    "dddd, YY-DD-MM",
    "dddd, YY-DD-MMM",
    "dddd, YY-DD-MMMM",
    "dddd, YYYY-D-M",
    "dddd, YYYY-D-Mo",
    "dddd, YYYY-D-MM",
    "dddd, YYYY-D-MMM",
    "dddd, YYYY-D-MMMM",
    "dddd, YYYY-Do-M",
    "dddd, YYYY-Do-Mo",
    "dddd, YYYY-Do-MM",
    "dddd, YYYY-Do-MMM",
    "dddd, YYYY-Do-MMMM",
    "dddd, YYYY-DD-M",
    "dddd, YYYY-DD-Mo",
    "dddd, YYYY-DD-MM",
    "dddd, YYYY-DD-MMM",
    "dddd, YYYY-DD-MMMM",
    "dddd, D/M",
    "dddd, D/Mo",
    "dddd, D/MM",
    "dddd, D/MMM",
    "dddd, D/MMMM",
    "dddd, Do/M",
    "dddd, Do/Mo",
    "dddd, Do/MM",
    "dddd, Do/MMM",
    "dddd, Do/MMMM",
    "dddd, DD/M",
    "dddd, DD/Mo",
    "dddd, DD/MM",
    "dddd, DD/MMM",
    "dddd, DD/MMMM",
    "dddd, M/YY",
    "dddd, M/YYYY",
    "dddd, Mo/YY",
    "dddd, Mo/YYYY",
    "dddd, MM/YY",
    "dddd, MM/YYYY",
    "dddd, MMM/YY",
    "dddd, MMM/YYYY",
    "dddd, MMMM/YY",
    "dddd, MMMM/YYYY",
    "dddd, D/M/YY",
    "dddd, D/M/YYYY",
    "dddd, D/Mo/YY",
    "dddd, D/Mo/YYYY",
    "dddd, D/MM/YY",
    "dddd, D/MM/YYYY",
    "dddd, D/MMM/YY",
    "dddd, D/MMM/YYYY",
    "dddd, D/MMMM/YY",
    "dddd, D/MMMM/YYYY",
    "dddd, Do/M/YY",
    "dddd, Do/M/YYYY",
    "dddd, Do/Mo/YY",
    "dddd, Do/Mo/YYYY",
    "dddd, Do/MM/YY",
    "dddd, Do/MM/YYYY",
    "dddd, Do/MMM/YY",
    "dddd, Do/MMM/YYYY",
    "dddd, Do/MMMM/YY",
    "dddd, Do/MMMM/YYYY",
    "dddd, DD/M/YY",
    "dddd, DD/M/YYYY",
    "dddd, DD/Mo/YY",
    "dddd, DD/Mo/YYYY",
    "dddd, DD/MM/YY",
    "dddd, DD/MM/YYYY",
    "dddd, DD/MMM/YY",
    "dddd, DD/MMM/YYYY",
    "dddd, DD/MMMM/YY",
    "dddd, DD/MMMM/YYYY",
    "dddd, M/D/YY",
    "dddd, M/D/YYYY",
    "dddd, M/Do/YY",
    "dddd, M/Do/YYYY",
    "dddd, M/DD/YY",
    "dddd, M/DD/YYYY",
    "dddd, Mo/D/YY",
    "dddd, Mo/D/YYYY",
    "dddd, Mo/Do/YY",
    "dddd, Mo/Do/YYYY",
    "dddd, Mo/DD/YY",
    "dddd, Mo/DD/YYYY",
    "dddd, MM/D/YY",
    "dddd, MM/D/YYYY",
    "dddd, MM/Do/YY",
    "dddd, MM/Do/YYYY",
    "dddd, MM/DD/YY",
    "dddd, MM/DD/YYYY",
    "dddd, MMM/D/YY",
    "dddd, MMM/D/YYYY",
    "dddd, MMM/Do/YY",
    "dddd, MMM/Do/YYYY",
    "dddd, MMM/DD/YY",
    "dddd, MMM/DD/YYYY",
    "dddd, MMMM/D/YY",
    "dddd, MMMM/D/YYYY",
    "dddd, MMMM/Do/YY",
    "dddd, MMMM/Do/YYYY",
    "dddd, MMMM/DD/YY",
    "dddd, MMMM/DD/YYYY",
    "dddd, M/D",
    "dddd, M/Do",
    "dddd, M/DD",
    "dddd, Mo/D",
    "dddd, Mo/Do",
    "dddd, Mo/DD",
    "dddd, MM/D",
    "dddd, MM/Do",
    "dddd, MM/DD",
    "dddd, MMM/D",
    "dddd, MMM/Do",
    "dddd, MMM/DD",
    "dddd, MMMM/D",
    "dddd, MMMM/Do",
    "dddd, MMMM/DD",
    "dddd, YY/M",
    "dddd, YY/Mo",
    "dddd, YY/MM",
    "dddd, YY/MMM",
    "dddd, YY/MMMM",
    "dddd, YYYY/M",
    "dddd, YYYY/Mo",
    "dddd, YYYY/MM",
    "dddd, YYYY/MMM",
    "dddd, YYYY/MMMM",
    "dddd, YY/M/D",
    "dddd, YY/M/Do",
    "dddd, YY/M/DD",
    "dddd, YY/Mo/D",
    "dddd, YY/Mo/Do",
    "dddd, YY/Mo/DD",
    "dddd, YY/MM/D",
    "dddd, YY/MM/Do",
    "dddd, YY/MM/DD",
    "dddd, YY/MMM/D",
    "dddd, YY/MMM/Do",
    "dddd, YY/MMM/DD",
    "dddd, YY/MMMM/D",
    "dddd, YY/MMMM/Do",
    "dddd, YY/MMMM/DD",
    "dddd, YYYY/M/D",
    "dddd, YYYY/M/Do",
    "dddd, YYYY/M/DD",
    "dddd, YYYY/Mo/D",
    "dddd, YYYY/Mo/Do",
    "dddd, YYYY/Mo/DD",
    "dddd, YYYY/MM/D",
    "dddd, YYYY/MM/Do",
    "dddd, YYYY/MM/DD",
    "dddd, YYYY/MMM/D",
    "dddd, YYYY/MMM/Do",
    "dddd, YYYY/MMM/DD",
    "dddd, YYYY/MMMM/D",
    "dddd, YYYY/MMMM/Do",
    "dddd, YYYY/MMMM/DD",
    "dddd, YY/D/M",
    "dddd, YY/D/Mo",
    "dddd, YY/D/MM",
    "dddd, YY/D/MMM",
    "dddd, YY/D/MMMM",
    "dddd, YY/Do/M",
    "dddd, YY/Do/Mo",
    "dddd, YY/Do/MM",
    "dddd, YY/Do/MMM",
    "dddd, YY/Do/MMMM",
    "dddd, YY/DD/M",
    "dddd, YY/DD/Mo",
    "dddd, YY/DD/MM",
    "dddd, YY/DD/MMM",
    "dddd, YY/DD/MMMM",
    "dddd, YYYY/D/M",
    "dddd, YYYY/D/Mo",
    "dddd, YYYY/D/MM",
    "dddd, YYYY/D/MMM",
    "dddd, YYYY/D/MMMM",
    "dddd, YYYY/Do/M",
    "dddd, YYYY/Do/Mo",
    "dddd, YYYY/Do/MM",
    "dddd, YYYY/Do/MMM",
    "dddd, YYYY/Do/MMMM",
    "dddd, YYYY/DD/M",
    "dddd, YYYY/DD/Mo",
    "dddd, YYYY/DD/MM",
    "dddd, YYYY/DD/MMM",
    "dddd, YYYY/DD/MMMM",
    "dddd, D.M",
    "dddd, D.Mo",
    "dddd, D.MM",
    "dddd, D.MMM",
    "dddd, D.MMMM",
    "dddd, Do.M",
    "dddd, Do.Mo",
    "dddd, Do.MM",
    "dddd, Do.MMM",
    "dddd, Do.MMMM",
    "dddd, DD.M",
    "dddd, DD.Mo",
    "dddd, DD.MM",
    "dddd, DD.MMM",
    "dddd, DD.MMMM",
    "dddd, M.YY",
    "dddd, M.YYYY",
    "dddd, Mo.YY",
    "dddd, Mo.YYYY",
    "dddd, MM.YY",
    "dddd, MM.YYYY",
    "dddd, MMM.YY",
    "dddd, MMM.YYYY",
    "dddd, MMMM.YY",
    "dddd, MMMM.YYYY",
    "dddd, D.M.YY",
    "dddd, D.M.YYYY",
    "dddd, D.Mo.YY",
    "dddd, D.Mo.YYYY",
    "dddd, D.MM.YY",
    "dddd, D.MM.YYYY",
    "dddd, D.MMM.YY",
    "dddd, D.MMM.YYYY",
    "dddd, D.MMMM.YY",
    "dddd, D.MMMM.YYYY",
    "dddd, Do.M.YY",
    "dddd, Do.M.YYYY",
    "dddd, Do.Mo.YY",
    "dddd, Do.Mo.YYYY",
    "dddd, Do.MM.YY",
    "dddd, Do.MM.YYYY",
    "dddd, Do.MMM.YY",
    "dddd, Do.MMM.YYYY",
    "dddd, Do.MMMM.YY",
    "dddd, Do.MMMM.YYYY",
    "dddd, DD.M.YY",
    "dddd, DD.M.YYYY",
    "dddd, DD.Mo.YY",
    "dddd, DD.Mo.YYYY",
    "dddd, DD.MM.YY",
    "dddd, DD.MM.YYYY",
    "dddd, DD.MMM.YY",
    "dddd, DD.MMM.YYYY",
    "dddd, DD.MMMM.YY",
    "dddd, DD.MMMM.YYYY",
    "dddd, M.D.YY",
    "dddd, M.D.YYYY",
    "dddd, M.Do.YY",
    "dddd, M.Do.YYYY",
    "dddd, M.DD.YY",
    "dddd, M.DD.YYYY",
    "dddd, Mo.D.YY",
    "dddd, Mo.D.YYYY",
    "dddd, Mo.Do.YY",
    "dddd, Mo.Do.YYYY",
    "dddd, Mo.DD.YY",
    "dddd, Mo.DD.YYYY",
    "dddd, MM.D.YY",
    "dddd, MM.D.YYYY",
    "dddd, MM.Do.YY",
    "dddd, MM.Do.YYYY",
    "dddd, MM.DD.YY",
    "dddd, MM.DD.YYYY",
    "dddd, MMM.D.YY",
    "dddd, MMM.D.YYYY",
    "dddd, MMM.Do.YY",
    "dddd, MMM.Do.YYYY",
    "dddd, MMM.DD.YY",
    "dddd, MMM.DD.YYYY",
    "dddd, MMMM.D.YY",
    "dddd, MMMM.D.YYYY",
    "dddd, MMMM.Do.YY",
    "dddd, MMMM.Do.YYYY",
    "dddd, MMMM.DD.YY",
    "dddd, MMMM.DD.YYYY",
    "dddd, M.D",
    "dddd, M.Do",
    "dddd, M.DD",
    "dddd, Mo.D",
    "dddd, Mo.Do",
    "dddd, Mo.DD",
    "dddd, MM.D",
    "dddd, MM.Do",
    "dddd, MM.DD",
    "dddd, MMM.D",
    "dddd, MMM.Do",
    "dddd, MMM.DD",
    "dddd, MMMM.D",
    "dddd, MMMM.Do",
    "dddd, MMMM.DD",
    "dddd, YY.M",
    "dddd, YY.Mo",
    "dddd, YY.MM",
    "dddd, YY.MMM",
    "dddd, YY.MMMM",
    "dddd, YYYY.M",
    "dddd, YYYY.Mo",
    "dddd, YYYY.MM",
    "dddd, YYYY.MMM",
    "dddd, YYYY.MMMM",
    "dddd, YY.M.D",
    "dddd, YY.M.Do",
    "dddd, YY.M.DD",
    "dddd, YY.Mo.D",
    "dddd, YY.Mo.Do",
    "dddd, YY.Mo.DD",
    "dddd, YY.MM.D",
    "dddd, YY.MM.Do",
    "dddd, YY.MM.DD",
    "dddd, YY.MMM.D",
    "dddd, YY.MMM.Do",
    "dddd, YY.MMM.DD",
    "dddd, YY.MMMM.D",
    "dddd, YY.MMMM.Do",
    "dddd, YY.MMMM.DD",
    "dddd, YYYY.M.D",
    "dddd, YYYY.M.Do",
    "dddd, YYYY.M.DD",
    "dddd, YYYY.Mo.D",
    "dddd, YYYY.Mo.Do",
    "dddd, YYYY.Mo.DD",
    "dddd, YYYY.MM.D",
    "dddd, YYYY.MM.Do",
    "dddd, YYYY.MM.DD",
    "dddd, YYYY.MMM.D",
    "dddd, YYYY.MMM.Do",
    "dddd, YYYY.MMM.DD",
    "dddd, YYYY.MMMM.D",
    "dddd, YYYY.MMMM.Do",
    "dddd, YYYY.MMMM.DD",
    "dddd, YY.D.M",
    "dddd, YY.D.Mo",
    "dddd, YY.D.MM",
    "dddd, YY.D.MMM",
    "dddd, YY.D.MMMM",
    "dddd, YY.Do.M",
    "dddd, YY.Do.Mo",
    "dddd, YY.Do.MM",
    "dddd, YY.Do.MMM",
    "dddd, YY.Do.MMMM",
    "dddd, YY.DD.M",
    "dddd, YY.DD.Mo",
    "dddd, YY.DD.MM",
    "dddd, YY.DD.MMM",
    "dddd, YY.DD.MMMM",
    "dddd, YYYY.D.M",
    "dddd, YYYY.D.Mo",
    "dddd, YYYY.D.MM",
    "dddd, YYYY.D.MMM",
    "dddd, YYYY.D.MMMM",
    "dddd, YYYY.Do.M",
    "dddd, YYYY.Do.Mo",
    "dddd, YYYY.Do.MM",
    "dddd, YYYY.Do.MMM",
    "dddd, YYYY.Do.MMMM",
    "dddd, YYYY.DD.M",
    "dddd, YYYY.DD.Mo",
    "dddd, YYYY.DD.MM",
    "dddd, YYYY.DD.MMM",
    "dddd, YYYY.DD.MMMM",
    "dddd, D M",
    "dddd, D Mo",
    "dddd, D MM",
    "dddd, D MMM",
    "dddd, D MMMM",
    "dddd, Do M",
    "dddd, Do Mo",
    "dddd, Do MM",
    "dddd, Do MMM",
    "dddd, Do MMMM",
    "dddd, DD M",
    "dddd, DD Mo",
    "dddd, DD MM",
    "dddd, DD MMM",
    "dddd, DD MMMM",
    "dddd, M YY",
    "dddd, M YYYY",
    "dddd, Mo YY",
    "dddd, Mo YYYY",
    "dddd, MM YY",
    "dddd, MM YYYY",
    "dddd, MMM YY",
    "dddd, MMM YYYY",
    "dddd, MMMM YY",
    "dddd, MMMM YYYY",
    "dddd, D M YY",
    "dddd, D M YYYY",
    "dddd, D Mo YY",
    "dddd, D Mo YYYY",
    "dddd, D MM YY",
    "dddd, D MM YYYY",
    "dddd, D MMM YY",
    "dddd, D MMM YYYY",
    "dddd, D MMMM YY",
    "dddd, D MMMM YYYY",
    "dddd, Do M YY",
    "dddd, Do M YYYY",
    "dddd, Do Mo YY",
    "dddd, Do Mo YYYY",
    "dddd, Do MM YY",
    "dddd, Do MM YYYY",
    "dddd, Do MMM YY",
    "dddd, Do MMM YYYY",
    "dddd, Do MMMM YY",
    "dddd, Do MMMM YYYY",
    "dddd, DD M YY",
    "dddd, DD M YYYY",
    "dddd, DD Mo YY",
    "dddd, DD Mo YYYY",
    "dddd, DD MM YY",
    "dddd, DD MM YYYY",
    "dddd, DD MMM YY",
    "dddd, DD MMM YYYY",
    "dddd, DD MMMM YY",
    "dddd, DD MMMM YYYY",
    "dddd, M D YY",
    "dddd, M D YYYY",
    "dddd, M Do YY",
    "dddd, M Do YYYY",
    "dddd, M DD YY",
    "dddd, M DD YYYY",
    "dddd, Mo D YY",
    "dddd, Mo D YYYY",
    "dddd, Mo Do YY",
    "dddd, Mo Do YYYY",
    "dddd, Mo DD YY",
    "dddd, Mo DD YYYY",
    "dddd, MM D YY",
    "dddd, MM D YYYY",
    "dddd, MM Do YY",
    "dddd, MM Do YYYY",
    "dddd, MM DD YY",
    "dddd, MM DD YYYY",
    "dddd, MMM D YY",
    "dddd, MMM D YYYY",
    "dddd, MMM Do YY",
    "dddd, MMM Do YYYY",
    "dddd, MMM DD YY",
    "dddd, MMM DD YYYY",
    "dddd, MMMM D YY",
    "dddd, MMMM D YYYY",
    "dddd, MMMM Do YY",
    "dddd, MMMM Do YYYY",
    "dddd, MMMM DD YY",
    "dddd, MMMM DD YYYY",
    "dddd, M D",
    "dddd, M Do",
    "dddd, M DD",
    "dddd, Mo D",
    "dddd, Mo Do",
    "dddd, Mo DD",
    "dddd, MM D",
    "dddd, MM Do",
    "dddd, MM DD",
    "dddd, MMM D",
    "dddd, MMM Do",
    "dddd, MMM DD",
    "dddd, MMMM D",
    "dddd, MMMM Do",
    "dddd, MMMM DD",
    "dddd, YY M",
    "dddd, YY Mo",
    "dddd, YY MM",
    "dddd, YY MMM",
    "dddd, YY MMMM",
    "dddd, YYYY M",
    "dddd, YYYY Mo",
    "dddd, YYYY MM",
    "dddd, YYYY MMM",
    "dddd, YYYY MMMM",
    "dddd, YY M D",
    "dddd, YY M Do",
    "dddd, YY M DD",
    "dddd, YY Mo D",
    "dddd, YY Mo Do",
    "dddd, YY Mo DD",
    "dddd, YY MM D",
    "dddd, YY MM Do",
    "dddd, YY MM DD",
    "dddd, YY MMM D",
    "dddd, YY MMM Do",
    "dddd, YY MMM DD",
    "dddd, YY MMMM D",
    "dddd, YY MMMM Do",
    "dddd, YY MMMM DD",
    "dddd, YYYY M D",
    "dddd, YYYY M Do",
    "dddd, YYYY M DD",
    "dddd, YYYY Mo D",
    "dddd, YYYY Mo Do",
    "dddd, YYYY Mo DD",
    "dddd, YYYY MM D",
    "dddd, YYYY MM Do",
    "dddd, YYYY MM DD",
    "dddd, YYYY MMM D",
    "dddd, YYYY MMM Do",
    "dddd, YYYY MMM DD",
    "dddd, YYYY MMMM D",
    "dddd, YYYY MMMM Do",
    "dddd, YYYY MMMM DD",
    "dddd, YY D M",
    "dddd, YY D Mo",
    "dddd, YY D MM",
    "dddd, YY D MMM",
    "dddd, YY D MMMM",
    "dddd, YY Do M",
    "dddd, YY Do Mo",
    "dddd, YY Do MM",
    "dddd, YY Do MMM",
    "dddd, YY Do MMMM",
    "dddd, YY DD M",
    "dddd, YY DD Mo",
    "dddd, YY DD MM",
    "dddd, YY DD MMM",
    "dddd, YY DD MMMM",
    "dddd, YYYY D M",
    "dddd, YYYY D Mo",
    "dddd, YYYY D MM",
    "dddd, YYYY D MMM",
    "dddd, YYYY D MMMM",
    "dddd, YYYY Do M",
    "dddd, YYYY Do Mo",
    "dddd, YYYY Do MM",
    "dddd, YYYY Do MMM",
    "dddd, YYYY Do MMMM",
    "dddd, YYYY DD M",
    "dddd, YYYY DD Mo",
    "dddd, YYYY DD MM",
    "dddd, YYYY DD MMM",
    "dddd, YYYY DD MMMM",
    "dddd, DM",
    "dddd, DMo",
    "dddd, DMM",
    "dddd, DMMM",
    "dddd, DMMMM",
    "dddd, DoM",
    "dddd, DoMo",
    "dddd, DoMM",
    "dddd, DoMMM",
    "dddd, DoMMMM",
    "dddd, DDM",
    "dddd, DDMo",
    "dddd, DDMM",
    "dddd, DDMMM",
    "dddd, DDMMMM",
    "dddd, MYY",
    "dddd, MYYYY",
    "dddd, MoYY",
    "dddd, MoYYYY",
    "dddd, MMYY",
    "dddd, MMYYYY",
    "dddd, MMMYY",
    "dddd, MMMYYYY",
    "dddd, MMMMYY",
    "dddd, MMMMYYYY",
    "dddd, DMYY",
    "dddd, DMYYYY",
    "dddd, DMoYY",
    "dddd, DMoYYYY",
    "dddd, DMMYY",
    "dddd, DMMYYYY",
    "dddd, DMMMYY",
    "dddd, DMMMYYYY",
    "dddd, DMMMMYY",
    "dddd, DMMMMYYYY",
    "dddd, DoMYY",
    "dddd, DoMYYYY",
    "dddd, DoMoYY",
    "dddd, DoMoYYYY",
    "dddd, DoMMYY",
    "dddd, DoMMYYYY",
    "dddd, DoMMMYY",
    "dddd, DoMMMYYYY",
    "dddd, DoMMMMYY",
    "dddd, DoMMMMYYYY",
    "dddd, DDMYY",
    "dddd, DDMYYYY",
    "dddd, DDMoYY",
    "dddd, DDMoYYYY",
    "dddd, DDMMYY",
    "dddd, DDMMYYYY",
    "dddd, DDMMMYY",
    "dddd, DDMMMYYYY",
    "dddd, DDMMMMYY",
    "dddd, DDMMMMYYYY",
    "dddd, MDYY",
    "dddd, MDYYYY",
    "dddd, MDoYY",
    "dddd, MDoYYYY",
    "dddd, MDDYY",
    "dddd, MDDYYYY",
    "dddd, MoDYY",
    "dddd, MoDYYYY",
    "dddd, MoDoYY",
    "dddd, MoDoYYYY",
    "dddd, MoDDYY",
    "dddd, MoDDYYYY",
    "dddd, MMDYY",
    "dddd, MMDYYYY",
    "dddd, MMDoYY",
    "dddd, MMDoYYYY",
    "dddd, MMDDYY",
    "dddd, MMDDYYYY",
    "dddd, MMMDYY",
    "dddd, MMMDYYYY",
    "dddd, MMMDoYY",
    "dddd, MMMDoYYYY",
    "dddd, MMMDDYY",
    "dddd, MMMDDYYYY",
    "dddd, MMMMDYY",
    "dddd, MMMMDYYYY",
    "dddd, MMMMDoYY",
    "dddd, MMMMDoYYYY",
    "dddd, MMMMDDYY",
    "dddd, MMMMDDYYYY",
    "dddd, MD",
    "dddd, MDo",
    "dddd, MDD",
    "dddd, MoD",
    "dddd, MoDo",
    "dddd, MoDD",
    "dddd, MMD",
    "dddd, MMDo",
    "dddd, MMDD",
    "dddd, MMMD",
    "dddd, MMMDo",
    "dddd, MMMDD",
    "dddd, MMMMD",
    "dddd, MMMMDo",
    "dddd, MMMMDD",
    "dddd, YYM",
    "dddd, YYMo",
    "dddd, YYMM",
    "dddd, YYMMM",
    "dddd, YYMMMM",
    "dddd, YYYYM",
    "dddd, YYYYMo",
    "dddd, YYYYMM",
    "dddd, YYYYMMM",
    "dddd, YYYYMMMM",
    "dddd, YYMD",
    "dddd, YYMDo",
    "dddd, YYMDD",
    "dddd, YYMoD",
    "dddd, YYMoDo",
    "dddd, YYMoDD",
    "dddd, YYMMD",
    "dddd, YYMMDo",
    "dddd, YYMMDD",
    "dddd, YYMMMD",
    "dddd, YYMMMDo",
    "dddd, YYMMMDD",
    "dddd, YYMMMMD",
    "dddd, YYMMMMDo",
    "dddd, YYMMMMDD",
    "dddd, YYYYMD",
    "dddd, YYYYMDo",
    "dddd, YYYYMDD",
    "dddd, YYYYMoD",
    "dddd, YYYYMoDo",
    "dddd, YYYYMoDD",
    "dddd, YYYYMMD",
    "dddd, YYYYMMDo",
    "dddd, YYYYMMDD",
    "dddd, YYYYMMMD",
    "dddd, YYYYMMMDo",
    "dddd, YYYYMMMDD",
    "dddd, YYYYMMMMD",
    "dddd, YYYYMMMMDo",
    "dddd, YYYYMMMMDD",
    "dddd, YYDM",
    "dddd, YYDMo",
    "dddd, YYDMM",
    "dddd, YYDMMM",
    "dddd, YYDMMMM",
    "dddd, YYDoM",
    "dddd, YYDoMo",
    "dddd, YYDoMM",
    "dddd, YYDoMMM",
    "dddd, YYDoMMMM",
    "dddd, YYDDM",
    "dddd, YYDDMo",
    "dddd, YYDDMM",
    "dddd, YYDDMMM",
    "dddd, YYDDMMMM",
    "dddd, YYYYDM",
    "dddd, YYYYDMo",
    "dddd, YYYYDMM",
    "dddd, YYYYDMMM",
    "dddd, YYYYDMMMM",
    "dddd, YYYYDoM",
    "dddd, YYYYDoMo",
    "dddd, YYYYDoMM",
    "dddd, YYYYDoMMM",
    "dddd, YYYYDoMMMM",
    "dddd, YYYYDDM",
    "dddd, YYYYDDMo",
    "dddd, YYYYDDMM",
    "dddd, YYYYDDMMM",
    "dddd, YYYYDDMMMM",
    "dddd, M Do, YY",
    "dddd, M Do, YYYY",
    "dddd, Mo Do, YY",
    "dddd, Mo Do, YYYY",
    "dddd, MM Do, YY",
    "dddd, MM Do, YYYY",
    "dddd, MMM Do, YY",
    "dddd, MMM Do, YYYY",
    "dddd, MMMM Do, YY",
    "dddd, MMMM Do, YYYY",
    "dddd, M D, YY",
    "dddd, M D, YYYY",
    "dddd, Mo D, YY",
    "dddd, Mo D, YYYY",
    "dddd, MM D, YY",
    "dddd, MM D, YYYY",
    "dddd, MMM D, YY",
    "dddd, MMM D, YYYY",
    "dddd, MMMM D, YY",
    "dddd, MMMM D, YYYY",
    "dddd, M DD, YY",
    "dddd, M DD, YYYY",
    "dddd, Mo DD, YY",
    "dddd, Mo DD, YYYY",
    "dddd, MM DD, YY",
    "dddd, MM DD, YYYY",
    "dddd, MMM DD, YY",
    "dddd, MMM DD, YYYY",
    "dddd, MMMM DD, YY",
    "dddd, MMMM DD, YYYY",

    // Unix Timestamps
    "x",
    "X",

    // Presets
    "L",
    "l",
    "LL",
    "ll",
    "LLL",
    "lll",
    "LLLL",
    "llll",
    "LT",

    // Single characters
    "d",
    "dd",
    "ddd",
    "dddd",
    "YY",
    "YYYY",
    "M",
    "Mo",
    "MM",
    "MMM",
    "MMMM",
    "Q",
    "Qo",
    "D",
    "Do",
    "DD",
    "DDD",
    "DDDo",
    "DDDD",
    "w",
    "wo",
    "ww"
];

const time_formats = [
    "H:m",
    "H:mm",
    "HH:m",
    "HH:mm",
    "h:m",
    "h:mm",
    "hh:m",
    "hh:mm",
    "m:s",
    "m:ss",
    "mm:s",
    "mm:ss",
    "H:m:s",
    "H:m:ss",
    "H:mm:s",
    "H:mm:ss",
    "HH:m:s",
    "HH:m:ss",
    "HH:mm:s",
    "HH:mm:ss",
    "h:m:s",
    "h:m:ss",
    "h:mm:s",
    "h:mm:ss",
    "hh:m:s",
    "hh:m:ss",
    "hh:mm:s",
    "hh:mm:ss",
    "H:m:s:S",
    "H:m:ss:S",
    "H:mm:s:S",
    "H:mm:ss:S",
    "HH:m:s:S",
    "HH:m:ss:S",
    "HH:mm:s:S",
    "HH:mm:ss:S",
    "h:m:s:S",
    "h:m:ss:S",
    "h:mm:s:S",
    "h:mm:ss:S",
    "hh:m:s:S",
    "hh:m:ss:S",
    "hh:mm:s:S",
    "hh:mm:ss:S",
    "H:m:s:S:SS",
    "H:m:ss:S:SS",
    "H:mm:s:S:SS",
    "H:mm:ss:S:SS",
    "HH:m:s:S:SS",
    "HH:m:ss:S:SS",
    "HH:mm:s:S:SS",
    "HH:mm:ss:S:SS",
    "h:m:s:S:SS",
    "h:m:ss:S:SS",
    "h:mm:s:S:SS",
    "h:mm:ss:S:SS",
    "hh:m:s:S:SS",
    "hh:m:ss:S:SS",
    "hh:mm:s:S:SS",
    "hh:mm:ss:S:SS",
    "H:m:s:S:SS:SSS",
    "H:m:ss:S:SS:SSS",
    "H:mm:s:S:SS:SSS",
    "H:mm:ss:S:SS:SSS",
    "HH:m:s:S:SS:SSS",
    "HH:m:ss:S:SS:SSS",
    "HH:mm:s:S:SS:SSS",
    "HH:mm:ss:S:SS:SSS",
    "h:m:s:S:SS:SSS",
    "h:m:ss:S:SS:SSS",
    "h:mm:s:S:SS:SSS",
    "h:mm:ss:S:SS:SSS",
    "hh:m:s:S:SS:SSS",
    "hh:m:ss:S:SS:SSS",
    "hh:mm:s:S:SS:SSS",
    "hh:mm:ss:S:SS:SSS",
    "Hm",
    "Hmm",
    "HHm",
    "HHmm",
    "hm",
    "hmm",
    "hhm",
    "hhmm",
    "ms",
    "mss",
    "mms",
    "mmss",
    "Hms",
    "Hmss",
    "Hmms",
    "Hmmss",
    "HHms",
    "HHmss",
    "HHmms",
    "HHmmss",
    "hms",
    "hmss",
    "hmms",
    "hmmss",
    "hhms",
    "hhmss",
    "hhmms",
    "hhmmss",
    "HmsS",
    "HmssS",
    "HmmsS",
    "HmmssS",
    "HHmsS",
    "HHmssS",
    "HHmmsS",
    "HHmmssS",
    "hmsS",
    "hmssS",
    "hmmsS",
    "hmmssS",
    "hhmsS",
    "hhmssS",
    "hhmmsS",
    "hhmmssS",
    "HmsSSS",
    "HmssSSS",
    "HmmsSSS",
    "HmmssSSS",
    "HHmsSSS",
    "HHmssSSS",
    "HHmmsSSS",
    "HHmmssSSS",
    "hmsSSS",
    "hmssSSS",
    "hmmsSSS",
    "hmmssSSS",
    "hhmsSSS",
    "hhmssSSS",
    "hhmmsSSS",
    "hhmmssSSS",
    "HmsSSSSSS",
    "HmssSSSSSS",
    "HmmsSSSSSS",
    "HmmssSSSSSS",
    "HHmsSSSSSS",
    "HHmssSSSSSS",
    "HHmmsSSSSSS",
    "HHmmssSSSSSS",
    "hmsSSSSSS",
    "hmssSSSSSS",
    "hmmsSSSSSS",
    "hmmssSSSSSS",
    "hhmsSSSSSS",
    "hhmssSSSSSS",
    "hhmmsSSSSSS",
    "hhmmssSSSSSS",
    // Single characters
    "H",
    "HH",
    "h",
    "hh",
    "m",
    "mm",
    "s",
    "ss",
    "Z",
    "ZZ",
    "S",
    "SS",
    "SSS"
];

module.exports = { date_formats, time_formats };
